In [1]:
import chromadb
import re
import unicodedata
import requests
import psycopg
from sqlalchemy import create_engine, text
from striprtf.striprtf import rtf_to_text
import pandas as pd

# chroma_client = chromadb.HttpClient(host='localhost', port=8000)
# chroma_client.heartbeat()

# collections = chroma_client.list_collections()

In [ ]:

# engine = create_engine(DATABASE_URL)

# with engine.connect() as conn:
#     result = conn.execute(text("SELECT 1"))
#     print(result.scalar())

# docs = pd.read_sql(
#     "SELECT * FROM documents LIMIT 5",
#     engine
# )

# docs

1

In [2]:
from striprtf.striprtf import rtf_to_text
import glob

rtf_texts = []

for file_path in glob.glob("../chroma/data/*.rtf"):
    with open(file_path, "r", encoding="utf-8", errors="ignore") as f:
        rtf_content = f.read()
        text = rtf_to_text(rtf_content)
        rtf_texts.append(text)

len(rtf_texts)

5

In [3]:
def clean_legal_text(text: str) -> str:
    """
    Clean court/legal text for RAG usage:
    - normalize unicode
    - remove non-breaking spaces
    - fix spaced words like
    - normalize whitespace
    - keep paragraph structure
    """

    if not text:
        return ""

    # 1. Unicode normalization
    text = unicodedata.normalize("NFKC", text)

    # 2. Replace non-breaking spaces and tabs
    text = text.replace("\xa0", " ").replace("\t", " ")

    # 3. Fix spaced-uppercase words (У Х В А Л А → УХВАЛА)
    text = re.sub(
        r'\b(?:[А-ЯІЇЄҐ]\s){2,}[А-ЯІЇЄҐ]\b',
        lambda m: m.group(0).replace(" ", ""),
        text
    )

    # 4. Remove excessive spaces
    text = re.sub(r'[ ]{2,}', ' ', text)

    # 5. Normalize newlines (max 2 in a row)
    text = re.sub(r'\n{3,}', '\n\n', text)

    # 6. Trim lines
    text = "\n".join(line.strip() for line in text.splitlines())

    # 7. Final trim
    return text.strip()

In [23]:
from langchain_text_splitters import RecursiveCharacterTextSplitter

splitter = RecursiveCharacterTextSplitter(chunk_size=500, 
                                          chunk_overlap=100,
                                          separators=["\n\n", "\n", ". ", " "])
chunks = splitter.split_text(clean_legal_text(rtf_texts[0]))

In [24]:
chunks

['Суддя Черняк В. Г.\n\nСправа No 646/449/25\nПровадження No 2/644/2708/25\n19.06.2025\n\nРІШЕННЯ\nІМЕНЕМУКРАЇНИ\n(заочне рішення)',
 '19 червня 2025 року м. Харків\nІндустріальний районний суд м. Харкова у складі:\nГоловуючого - судді Черняка В. Г.,\nза участю:\nсекретаря судових засідань –Юр`єва Є.Д.,\nрозглянувши у відкритому судовому засіданні в залі суду в м. Харкові в порядку спрощеного позовного провадження цивільну справу за позовом Товариства з обмеженою відповідальністю «Фінансова компанія «Кредит капітал» до ОСОБА_1 про стягнення заборгованості,-\nу с т а н о в и в :',
 'Позивач ТОВ "ФК «Кредит капітал» через систему «Електронний суд» звернулося до суду з позовом до ОСОБА_1 про стягнення заборгованості за кредитним договором. Позовні вимоги мотивовані тим, що 03.12.2022 року між Товариством з обмеженою відповідальністю «Лінеура Україна» та ОСОБА_1 укладено договір про надання коштів на умовах споживчого кредиту No 3307920',
 '. 13.09.2023 року ТОВ «Лінеура Україна» та ТОВ «Фінансова Компанія «Кредит-Капітал» уклали Договір факторингу No ККЛУ-13092023, згідно якого ТОВ «Фінансова Компанія «Кредит-Капітал» набуло статусу нового кредитора та отримало право грошової вимоги по відношенню до осіб, які були боржниками ТОВ «Лінеура Україна», включно і до ОСОБА_1 за договором про надання коштів на умовах споживчого кредиту No 3307920 від 03.12.2022 року.',
 'Станом на день звернення до суду з даним позовом заборгованість за договором відповідачем не погашається, проценти за користування кредитними коштами не сплачуються, у зв`язку з чим у відповідача обліковується прострочена заборгованість.\nВраховуючи викладене вище, позивач просить суд стягнути з ОСОБА_1 заборгованість у розмірі 37 581 грн., а також витрати по сплаті судового збору в розмірі 2 422,40 грн.',
 'Ухвалою Орджонікідзевського районного суду м. Харкова від 11.04.2025 відкрито провадження у справі в порядку спрощеного позовного провадження з повідомленням (викликом) сторін, призначено судове засідання по справі.\nПредставник позивача в судове засідання не з`явився, в позовній заяві просив розглянути справу за його відсутності, позовні вимоги підтримав.',
 'Відповідач ОСОБА_1 у судове засідання не з`явилась, про дату, час і місце розгляду справи була повідомлена своєчасно і належним чином. Будь-яких заяв та клопотань від відповідача не надходило, процесуальним правом на подання відзиву на позовну заяву відповідач не скористався.\nВідповідно до вимог ч. 8 ст. 178 ЦПК України у разі ненадання відповідачем відзиву у встановлений судом строк без поважних причин, суд вирішує справу за наявними матеріалами.',
 'Враховуючи, що відповідач належним чином повідомлений про час і місце судового розгляду справи, суд вважає можливим розглянути справу за відсутності відповідача та ухвалити заочне рішення на підставі наявних у справі доказів, що відповідає положенням ст. 280 ЦПК України.\nУраховуючи, що в судове засідання не з`явилися всі учасники справи, відповідно до ч. 2 ст. 247 ЦПК України, фіксування судового процесу за допомогою звукозаписувального технічного засобу не здійснювалось.',
 'Суд, дослідивши надані докази у їх сукупності, встановив такі обставини та відповідні їм правовідносини, що виникли між сторонами.\nСудом встановлено, що 03 грудня 2022 року між ТОВ «Лінеура Україна» та ОСОБА_1 було укладено договір No3307920 про надання коштів на умовах споживчого кредиту, який останнім підписано із застосуванням електронного підпису одноразовим ідентифікатором Х912, який був надісланий на номер мобільного телефону відповідача.',
 'Відповідно до п.п. 1.2-1.3 Кредитного договору, на умовах, встановлених договором, Товариство зобов`язується надати Клієнту грошові кошти в гривні на умовах строковості, зворотності, платності, а клієнт зобов`язується повернути кредит, сплатити проценти за користування кредитом та виконати інші обов`язки, передбачені договором. Тип кредиту – кредит. Сума кредиту (загальний розмір) складає: 6 000,00 гривень. Строк кредиту 360 днів',
 '. Сума кредиту (загальний розмір) складає: 6 000,00 гривень. Строк кредиту 360 днів. Детальні терміни повернення кредиту та сплати процентів визначені в Таблиці обчислення загальної вартості кредиту для споживача та реальної річної процентної ставки за договором про споживчий кредит, що є Додатком No1 до цього договору. Графік платежів розраховується за зниженою процентною ставкою, виходячи з припущення, що споживач виконає свої обов`язки на умовах та у строки, визначені в договорі.',
 'Строк кредиту, а також термін (дата) повернення (виплати) кредиту, встановлені договором, продовженню не підлягають (п.1.3.1 Договору).\nТип процентної ставки – фіксована. Стандартна процента ставка становить 1,99% в день, занижена процентна ставка – 1,19 % в день (п.1.4.1 – п.1.4.2 Договору).',
 'Згідно п. 2.1 Кредит надається Товариством у безготівковій формі шляхом перерахування коштів кредиту за реквізитами платіжної картки No НОМЕР_1 або іншої платіжної картки Клієнта, реквізити якої надані Клієнтом Товариству з метою отримання кредиту. Дата надання кредиту 03.12.2022 або 04.12.2022 (п.2.2 Договору).',
 'Така ж інформація стосовно розміру кредиту, строку його повернення, відсотків за користування кредитом була доведена відповідачу у паспорті споживчого кредиту, який підписаний електронним підписом - одноразовим ідентифікатором Х912.\nГрафіком платежів за договором No 3307920 доведено до відома ОСОБА_1 графік погашення заборгованості, інформацію про загальну вартість кредиту, реальну річну процентну ставку, суму процентів за користування кредитом.',
 'На підтвердження виконання Товариством п. 2.1 Кредитного договору, позивач надав інформаційну довідку ТОВ «Пейтек Україна» від 04.03.2024 року, відповідно до якої 03.12.2022 року на картковий рахунок відповідача було перераховано кредитні кошти в сумі 6000,00 грн. за реквізитами платіжної картки No НОМЕР_1 .',
 'Згідно п.1.1 Договору, укладення цього договору здійснюється сторонами за допомогою ІТС Товариства, доступ до якої забезпечується клієнту через Веб-сайт або мобільний додаток «Credit7». Електронна ідентифікація клієнта здійснюється при вході клієнта в Особистий кабінет, в порядку передбаченому Законом України «Про електронну комерцію».',
 '13 вересня 2023 року між ТОВ «Лінеура Україна» та ТОВ «ФК «Кредит-Капітал» укладено договір факторингу NoККЛУ-13092023, відповідно до умов якого ТОВ «Лінеура Україна» передає (відступає) ТОВ «ФК «Кредит-Капітал» за плату, а ТОВ «ФК «Кредит-Капітал» приймає належні ТОВ «Лінеура Україна» права грошової вимоги до боржників у Реєстрі боржників, про що також був складений акт приймання-передачі реєстру божників від 13 вересня 2023.',
 'Відповідно до витягу з Реєстру боржників до договору факторингу NoККЛУ-13092023, від ТОВ «Лінеура Україна» до ТОВ «ФК «Кредит-Капітал» перейшло право вимоги до ОСОБА_1 за кредитним договором No3307920 від 03 грудня 2022 року на загальну суму 37 581 гривень.\nЩодо погашення заборгованості за кредитним договором позивачем направлено відповідачу досудову вимогу No23053403 від 24.12.2024 року.',
 'Згідно з наданим позивачем розрахунком, заборгованість ОСОБА_1 за кредитним договором No3307920 від 03 грудня 2022 року станом на 13 вересня 2023 року становить 37 581 грн. та складається з наступного: заборгованість за тілом кредиту – 6 000 грн.; заборгованість за відсотками – 31 581 грн.\nЗгідно з статтею 512 ЦК України кредитор у зобов`язанні може бути замінений іншою особою внаслідок передання ним своїх прав іншій особі за правочином (відступлення права вимоги).',
 'Відповідно до статті 514 ЦК України до нового кредитора переходять права первісного кредитора у зобов`язанні в обсязі і на умовах, що існували на момент переходу цих прав, якщо інше не встановлено договором або законом.',
 'Згідно з статтею 1077 ЦК України за договором факторингу (фінансування під відступлення права грошової вимоги) одна сторона (фактор) передає або зобов`язується передати грошові кошти в розпорядження другої сторони (клієнта) за плату (у будь-який передбачений договором спосіб), а клієнт відступає або зобов`язується відступити факторові своє право грошової вимоги до третьої особи (боржника).',
 'Наявними у матеріалах справи доказами підтверджується факт переходу права грошової вимоги від первісного кредитора до ТОВ «ФК «Кредит-Капітал» за договором No3307920 про надання коштів на умовах споживчого кредиту, укладеним між ТОВ «Лінеура Україна» та ОСОБА_1 .',
 'Відповідно до частин першої, третьої статті 509 ЦК України зобов`язанням є правовідношення, в якому одна сторона (боржник) зобов`язана вчинити на користь другої сторони (кредитора) певну дію (передати майно, виконати роботу, надати послугу, сплатити гроші тощо) або утриматися від певної дії, а кредитор має право вимагати від боржника виконання його обов`язку. Зобов`язання має ґрунтуватися на засадах добросовісності, розумності та справедливості.',
 'Згідно з статтею 526 ЦК України зобов`язання має виконуватися належним чином відповідно до умов договору та вимог цього Кодексу, інших актів цивільного законодавства, а за відсутності таких умов та вимог - відповідно до звичаїв ділового обороту або інших вимог, що звичайно ставляться.\nВідповідно до статті 610 ЦК України порушенням зобов`язання є його невиконання або виконання з порушенням умов, визначених змістом зобов`язання (неналежне виконання).',
 'Статтею 611 ЦК України у разі порушення зобов`язання настають правові наслідки, встановлені договором чи законом, зокрема: 1) припинення зобов`язання внаслідок односторонньої відмови від зобов`язання, якщо це встановлено договором або законом, або розірвання договору; 2) зміна умов зобов`язання; 3) сплата неустойки; 4) відшкодування збитків та моральної шкоди.',
 'За змістом статей 626, 628 ЦК України договором є домовленість двох або більше сторін, спрямована на встановлення, зміну або припинення цивільних прав та обов`язків. Зміст договору становлять умови (пункти), визначені на розсуд сторін і погоджені ними, та умови, які є обов`язковими відповідно до актів цивільного законодавства.\nЗгідно з частиною першою статті 1049 ЦК України позичальник зобов`язаний повернути позикодавцеві позику у строк та в порядку, що встановлено договором.',
 'Відповідно до частини другої статті 1050 ЦК України, в разі прострочення повернення чергової частини позики кредитор має право вимагати від боржника дострокового повернення частини позики, що залишилася, та сплати відсотків за користування кредитом.',
 'Відповідно до частини першої статті 1054 ЦК України за кредитним договором банк або інша фінансова установа (кредитодавець) зобов`язується надати грошові кошти (кредит) позичальникові у розмірах та на умовах, встановлених договором, а позичальник зобов`язується повернути кредит та сплатити проценти (частина перша статті 1048 ЦК України).\nКредитний договір укладається у письмовій формі (стаття 1055 ЦК України).',
 'Кредитний договір укладається у письмовій формі (стаття 1055 ЦК України).\nВідповідно до частин першої, другої статті 207 ЦК України правочин вважається таким, що вчинений у письмовій формі, якщо його зміст зафіксований в одному або кількох документах, у листах, телеграмах, якими обмінялися сторони. Правочин вважається таким, що вчинений у письмовій формі, якщо він підписаний його стороною (сторонами).',
 'Враховуючи положення ч.1 ст. 5 Закону України «Про електронні документи та електронний документообіг», правочин вважається вчиненим у електронній формі у випадку, якщо в ньому наявні всі обов`язкові реквізити документа.\nУ статті 3 Закону України «Про електронну комерцію» зазначено, що електронний договір - це домовленість двох або більше сторін, спрямована на встановлення, зміну або припинення цивільних прав і обов`язків та оформлена в електронній формі.',
 'Також, відповідно до ч. 1, 2 ст. 6 Закону України «Про електронні документи та електронний документообіг», електронний підпис є обов`язковим реквізитом електронного документа, який використовується для ідентифікації автора та/або підписувача електронного документа іншими суб`єктами електронного документообігу. Накладанням електронного підпису завершується створення електронного документа.',
 'Електронний підпис одноразовим ідентифікатором - це дані в електронній формі у вигляді алфавітно-цифрової послідовності, що додаються до інших електронних даних особою, яка прийняла пропозицію (оферту) укласти електронний договір, та надсилаються іншій стороні цього договору (п. 6 ч. 1 ст. 3 Закону України «Про електронну комерцію»).',
 'Одноразовий ідентифікатор може передаватися суб`єктом електронної комерції, що пропонує укласти договір, іншій стороні електронного правочину засобом зв`язку, вказаним під час реєстрації у його системі, та додається (приєднується) до електронного повідомлення від особи, яка прийняла пропозицію укласти договір.',
 'З врахуванням викладеного, наявність електронних підписів сторін підтверджує їх волю, спрямовану на набуття, зміну або припинення цивільних прав та обов`язків, забезпечує ідентифікацію сторін та цілісність документа, в якому втілюється воля останніх.',
 'Суд установив, що між відповідачем ОСОБА_1 та ТОВ «Лінеура Україна» було укладено договір No3307920 про надання коштів на умовах споживчого кредиту від 03 грудня 2022 року в електронній формі, який підписаний відповідачем за допомогою електронного підпису одноразовим ідентифікатором (одноразовим паролем).',
 'Відповідно до умов договору ТОВ «Лінеура Україна» надало відповідачу кошти в сумі 6 000 грн. строком на 360 днів, а останній зобов`язався повернути кошти та сплатити відсотки за користування ними, розмір яких визначений договором.\n03 грудня 2022 року кредитні кошти були перераховані відповідачу.\nОтже, факт отримання відповідачем коштів у ТОВ «Лінеура Україна» суд вважає доведеним.',
 'У підписаному відповідачем договорі No3307920 про надання споживчого кредиту від 03 грудня 2022 року визначена сума кредиту, проценти за користування кредитними коштами, строк повернення коштів, отже між сторонами було досягнуто згоди щодо істотних умов кредитного договору, такий правочин, згідно з вимогами статті 204 ЦК України, створює презумпцію правомірності правочину, у зв`язку з чим договір, згідно зі статтею 629 ЦК України є обов`язковим для виконання сторонами, а зобов`язання за ним,',
 'згідно зі статтею 629 ЦК України є обов`язковим для виконання сторонами, а зобов`язання за ним, відповідно до приписів статті 526 ЦК України, мають виконуватися належним чином відповідно до закону та умов договору.',
 'Відповідач свої зобов`язання за договором не виконав, оскільки в повному обсязі не повернув ні первинному кредитору, ні позивачу кредитні кошти, проценти за користування ними, внаслідок чого виникла заборгованість договором No3307920 від 03 грудня 2022 року, яка становить 37 581 грн.\nЗгідно статтею 81 ЦПК України кожна сторона повинна довести ті обставини, на які вона посилається як на підставу своїх вимог або заперечень, крім випадків, встановлених цим Кодексом.',
 'Метою доказування є з`ясування дійсних обставин справи, обов`язок доказування покладається на сторін, суд за власною ініціативою не може збирати докази. Це положення є одним з найважливіших наслідків принципу змагальності у цивільному процесі.\nРозмір вказаної заборгованості за кредитним договором відповідач не спростував, власного контррозрахунку не надав. Доказів про належне виконання умов кредитного договору не надав.',
 'Відтак, суд вважає, що позов є обґрунтованим, позовні вимоги є доведеними, а тому із ОСОБА_1 підлягає стягненню заборгованість за кредитним договором у повному обсязі.',
 'Питання про розподіл судових витрат суд вирішує відповідно до вимог ст. 141 ЦПК України, а саме судовий збір покладається на сторони пропорційно розміру задоволених позовних вимог. Оскільки суд дійшов висновку про задоволення позовних вимог позивача в повному обсязі, з відповідача на користь позивача підлягають стягненню витрати по сплаті судового збору в сумі 2 422,40 гривень.',
 'На підставі викладеного, керуючись ст.2,12,13,81, 89, 247, 258-259,263-265, 280-283 ЦПК України, ст.ст. 512, 514, 516, 525, 526, 527, 530, 610, 611, 617, 625, 629, 638, 1048, 1049, 1054, 1077, 1078, 1084 ЦК України, суд –',
 'в и р і ш и в :\nПозов Товариства з обмеженою відповідальністю «Фінансова компанія «Кредит капітал» до ОСОБА_1 про стягнення заборгованості - задовольнити.',
 'Стягнути з ОСОБА_1 на користь Товариства з обмеженою відповідальністю «Фінансова компанія «Кредит капітал» заборгованість за договором No3307920 про надання коштів на умовах споживчого кредиту від 03 грудня 2022 року, яка станом на 13 вересня 2023 року становить 37 581 грн. та складається з наступного: заборгованість за тілом кредиту – 6 000 грн.; заборгованість за відсотками – 31 581 грн.',
 'Стягнути з ОСОБА_1 на користь Товариства з обмеженою відповідальністю «Фінансова компанія «Кредит капітал» витрати по сплаті судового збору в сумі 2 442 гривень 40 копійок.',
 'Позивач має право оскаржити заочне рішення в загальному порядку, встановленому цим Кодексом.\nАпеляційна скарга на рішення суду може бути подана протягом тридцяти днів, з дня проголошення рішення до Харківського апеляційного суду, а якщо в судовому засіданні було оголошено лише вступну та резолютивну частини судового рішення або у разі розгляду справи (вирішення питання) без повідомлення (виклику) учасників справи, зазначений строк обчислюється з дня складення повного судового рішення,',
 'Заочне рішення може бути переглянуте судом, що його ухвалив, за письмовою заявою відповідача. Заяву про перегляд заочного рішення може бути подано протягом тридцяти днів з дня його проголошення. Учасник справи, якому повне заочне рішення суду не було вручене у день його проголошення, має право на поновлення пропущеного строку на подання заяви про його перегляд - якщо така заява подана протягом двадцяти днів з дня вручення йому повного заочного рішення суду.',
 'Заочне рішення набирає законної сили, якщо протягом строків, встановлених цим Кодексом, не подані заява про перегляд заочного рішення або апеляційна скарга, або якщо рішення залишено в силі за результатами апеляційного розгляду справи.',
 'Учасники справи:\nПозивач: ТОВАРИСТВО З ОБМЕЖЕНОЮ ВІДПОВІДАЛЬНІСТЮ "ФІНАНСОВА КОМПАНІЯ "КРЕДИТ- КАПІТАЛ", адреса Україна, 79029, Львівська обл., місто Львів, ВУЛИЦЯ СМАЛЬ-СТОЦЬКОГО, будинок 1, корпус 28 ЄДРПОУ 3523423 ;\nВідповідач: ОСОБА_1 , ІНФОРМАЦІЯ_1 , РНОКПП НОМЕР_2 , зареєстроване місце проживання: АДРЕСА_1 .\n\nСуддя: Черняк В.Г.\n\n\n\x00']

In [ ]:
from chromadb.utils.embedding_functions import OpenAIEmbeddingFunction

collection = chroma_client.create_collection(
    name="new_gen_docs",
    embedding_function=OpenAIEmbeddingFunction(
        api_key=
        model_name="text-embedding-3-large"
    )
)

In [17]:
collection.peek()

{'ids': [],
 'embeddings': array([], dtype=float64),
 'metadatas': [],
 'documents': [],
 'data': None,
 'uris': None,
 'included': ['metadatas', 'documents', 'embeddings']}

In [ ]:
# collection = chroma_client.get_collection(
#     name='test_collection_v2',
# )

In [25]:
docs.head(1)

,doc_id,court_code,judgment_code,justice_kind,category_code,cause_num,adjudication_date,receipt_date,judge,doc_url,status,date_publ
0,124212035,227,5.0,1.0,40356.0,149/4141/24,2025-01-02 00:00:00+02,2025-01-04 00:00:00+02,Олійник І. В.,http://od.reyestr.court.gov.ua/files/62/90134c...,1,2025-01-06 00:00:00+02

In [37]:
from tqdm import tqdm

doc_text = []
metadatas = []
ids = []

for _, row in tqdm(docs.iterrows()):

    cl_text = extract_rtf_text(row["doc_url"])
    doc_text.append(cl_text)

    metadatas.append({
        "doc_id": int(row["doc_id"]),
        "cause_num": row["cause_num"],
        "judge": row["judge"],
        "court_code": row["court_code"],
        "date": row["date_publ"]

    })

    ids.append(str(row["doc_id"]))

5it [00:00, 14.84it/s]

In [38]:
collection.add(
    documents=doc_text,
    metadatas=metadatas,
    ids=ids,
)

BadRequestError: Error code: 400 - {'error': {'message': "This model's maximum context length is 8192 tokens, however you requested 10290 tokens (10290 in your prompt; 0 for the completion). Please reduce your prompt; or completion length.", 'type': 'invalid_request_error', 'param': None, 'code': None}} in add.

In [5]:
collection.add(
    documents = [rtf_texts[0], rtf_texts[1], rtf_texts[2], rtf_texts[3]],
    metadatas = [{"source": "149/3813/25"},{"source": "149/4141/24"},{'source':'149/339/25'},{'source':'149/6/25'}],
    ids = ["id1", "id2", "id3", "id4"]
)

{'ids': ['id1', 'id2', 'id3', 'id4'],
 'embeddings': array([[ 0.02162955,  0.04352154, -0.05550636, ...,  0.00302354,
          0.0126956 ,  0.01563713],
        [ 0.02045577,  0.03636581, -0.05015524, ..., -0.01164706,
         -0.00625309,  0.02731786],
        [ 0.00720943,  0.01756578, -0.02543858, ..., -0.01258771,
          0.00152275,  0.03695174],
        [ 0.00384395,  0.05690486, -0.0745467 , ...,  0.01200441,
         -0.00283529,  0.01644803]], shape=(4, 1536)),
 'metadatas': [{'source': '149/3813/25'},
  {'source': '149/4141/24'},
  {'source': '149/339/25'},
  {'source': '149/6/25'}],
 'documents': ['\nУ Х В А Л А\nСправа № 149/3813/25\nПровадження №1-кс/149/687/25\n\n24.11.2025 р. \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 м. Хмільник\nХмільницький міськрайонний суд Вінницької області в складі:\nслідчого судді ОСОБА_1 ,\nза участі секретаря ОСОБА_2 ,\nпрокурора ОСОБА_3 (приймає участь в режимі відеоконференції)\nслідчого ОСОБА_4 ,\nзахисника адвоката ОСОБА_5 ,\nпідозрюваного ОСОБА_6 ,\nрозглянувши у судовому засіданні клопотання слідчої СВ Хмільницького РВП ГУНП у Вінницькій області ОСОБА_7 про застосування запобіжного заходу у вигляді тримання під вартою, заявлене у кримінальному провадженні № 42023052210000216, внесеному до Єдиного реєстру досудових розслідувань 29.05.2023, за ознаками кримінального правопорушення, передбаченого ч. 4\xa0ст. 408 КК України, стосовно\nОСОБА_6 , ІНФОРМАЦІЯ_1 , громадянина України, не одруженого, проживаючого за адресою: АДРЕСА_1 \n\nВСТАНОВИВ:\n24.11.2025 до Хмільницького міськрайонного суду Вінницької області надійшло вказане клопотання, яке мотивовано тим, що ОСОБА_6 обґрунтовано підозрюється у вчиненні кримінального правопорушення, передбаченого ч. 4 ст. 408 КК України, яке, відповідно до\xa0ст. 12 КК України, є особливо тяжким злочином. В ході досудового розслідування встановлено наявність ризиків, передбачених п.п. 1, 3 ч. 1\xa0ст. 177 КПК України, а тому слідча, за погодженням із прокурором, просить застосувати до підозрюваного запобіжний захід у вигляді тримання під вартою строком 60 днів.\nСлідчий та прокурор у судовому засіданні підтримали клопотання.\nЗахисник та підозрюваний у судовому засіданні заперечили проти задоволення клопотання та просили обрати більш м`який запобіжний захід, зокрема у виді домашнього арешту в нічний період доби або заставу, оскільки підозрюваний здійснює догляд за своєю бабусею.\nСлідчий суддя, вислухавши думку учасників процесу, дослідивши матеріали клопотання, дійшов висновку, що клопотання підлягає задоволенню, враховуючи наступне.\n29.05.2023 до ЄРДР за № 42023052210000216 внесено відомості за фактом вчинення ОСОБА_6 кримінального правопорушення, передбаченого ч. 4 ст. 408 КК України.\n21.07.2025 ОСОБА_6 повідомлено про підозру у вчиненні кримінального правопорушення, передбаченого ч. 4 ст. 408 КК України, а 22.11.2025 про зміну раніше повідомленої підозри.\n22.11.2025 о 10:58 год ОСОБА_6 затримано на підставі\xa0ст. 208 КПК України.\nПід час розгляду клопотання про застосування запобіжного заходу встановлено, що надані сторонами кримінального провадження докази доводять обставини, які свідчать про обґрунтовану підозру у вчиненні підозрюваним кримінального правопорушення, передбаченого ч. 4\xa0ст. 408 КК України, що підтверджується: витягом з ЄРДР; документами щодо проходження підозрюваним військової служби, а також наказами про зарахування та відрахування з військових частин, актами службових розслідувань; іншими зібраними доказами.\nІснують ризики, передбачені п.п. 1, 3 ч. 1 ст. 177 КПК України, на які вказує у своєму клопотанні слідча, що полягають у необхідності запобігання спробам підозрюваного переховуватися від органів досудового розслідування та/або суду; незаконно впливати на свідків у цьому ж кримінальному провадженні.\nПри цьому, суд враховує вагомість наявних доказів про вчинення підозрюваним вказаного кримінального правопорушення, тяжкість покарання, що загрожує у разі визнання його винуватим у вчиненні кримінального правопорушення, його вік, стан здоров`я.\nСуд відхиляє доводи сторони захисту про можливість застосування більш м`якого запобіжного заходу, оскільки ч. 8\xa0ст. 176 КПК України\xa0визначено, що під час дії воєнного стану до військовослужбовців, які підозрюються або обвинувачуються у вчиненні злочинів, передбачених статтями\xa0402-405,\xa0407,\xa0408,\xa0429 Кримінального кодексу України, застосовується виключно запобіжний захід, визначений пунктом 5 частини першої цієї статті. Враховуючи те, що на даний час діє воєнний стан, до підозрюваного за\xa0ст. 408 КК України\xa0може бути застосовано лише тримання під вартою. Окрім того, суд враховує, що підозрюваний оголошувався в розшук. \nКримінальне правопорушення, яке інкриміноване ОСОБА_6 , за відомостями слідства вчинено 20.01.2023. Та обставина, що ОСОБА_6 на даний час оформив догляд за бабусею не є підставою для звільнення від кримінальної відповідальності. При цьому, як встановлено з довідок у с. Іванів зареєстровано 11 осіб, які входять до складу його сім`ї. Доказів того, що догляд за бабусею може здійснювати виключно ОСОБА_6 суду не надано.\nЗгідно з п. 4 ч. 2\xa0ст. 183 КПК України\xa0запобіжний захід у вигляді тримання під вартою не може бути застосований, окрім як, зокрема, до раніше не судимої особи, яка підозрюється або обвинувачується у вчиненні злочину, за який законом передбачено покарання у виді позбавлення волі на строк понад п`ять років.\nВраховуючи викладене та приймаючи до уваги встановлені обставини, слідчий суддя доходить висновку про наявність підстав для задоволення клопотання та обрання підозрюваному запобіжного заходу у вигляді тримання під вартою.\nПри цьому, слідчий суддя, у відповідності до абз. 8 ч. 4\xa0ст. 183 КПК України, не вважає необхідне визначати розмір застави, оскільки кримінальне провадження порушено за фактом вчинення злочину, передбаченого\xa0ст. 408 КК України.\nНа підставі вищевикладеного і керуючись ст.ст.\xa0177,\xa0178,\xa0181,\xa0183,\xa0184,\xa0193,\xa0194,\xa0395 КПК України,\n\nУХВАЛИВ:\nКлопотання слідчої СВ Хмільницького РВП ГУНП у Вінницькій області ОСОБА_7 про застосування запобіжного заходу у вигляді тримання під вартою - задовольнити.\nЗастосувати до ОСОБА_6 запобіжний захід у вигляді тримання під вартою строком 60 днів, тобто до 10:58 год 20.01.2026.\nСтрок тримання ОСОБА_6 під вартою рахувати з моменту затримання, тобто 10:58 год 22.11.2025.\nУхвала слідчого судді підлягає негайному виконанню після її проголошення.\nУхвала слідчого судді може бути оскаржена до Вінницького апеляційного суду протягом 5 днів з дня її оголошення, однак оскарження ухвали не зупиняє її виконання.\n\nСлідчий суддя\xa0\xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0\xa0 ОСОБА_8 \n\n\n\n\n\n\n\x00',
  '\nСправа № 149/4141/24\nПровадження №2/149/196/25 \nНомер рядка звіту 48\n\xa0 У\xa0Х В\xa0А Л\xa0А \n"02" січня 2025 р. \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0м. Хмільник\nСуддя Хмільницького міськрайонного суду Вінницької області Олійник І. В., перевіривши матеріали справи за позовом Державної екологічної інспекції у Вінницькій області, третя особа, яка не заявляє самостійних вимог щодо предмета спору на стороні позивача: Уланівська сільська рада Хмільницького району Вінницької області до ОСОБА_1 про відшкодування шкоди, завданої державі внаслідок порушення природоохоронного законодавства,\n\nВСТАНОВИВ:\nДо Хмільницького міськрайонного суду Вінницької області надійшла вказана позовна заява.\nДослідивши матеріали, суддя дійшов висновку про передачу її за підсудністю, з огляду на наступне.\nЗгідно із ч. 1 ст. 27 ЦПК України позови до фізичної особи пред`являються в суд за зареєстрованим у встановленому законом порядку місцем її проживання або перебування, якщо інше не передбачено законом.\nВідповідно до інформації з Єдиного державного демографічного реєстру № 1004293 від 01.01.2025 встановлено, що відповідач зареєстрована за адресою: АДРЕСА_1 , що належить до територіальної юрисдикції (підсудності) Вінницького міського суду Вінницької області.\nЗгідно із п. 3, п. 3-1 розділу ХІІ "Прикінцеві та перехідні положення" Закону України "Про судоустрій і статус суддів", районні, міжрайонні, районні у містах, міські, міськрайонні суди продовжують здійснювати свої повноваження до утворення та початку діяльності місцевого окружного суду, юрисдикція якого розповсюджується на відповідну територію. До набрання чинності законом України щодо зміни системи місцевих судів на території України у зв`язку з утворенням (ліквідацією) районів відповідні місцеві суди продовжують здійснювати свої повноваження у межах територіальної юрисдикції, визначеної до набрання чинності Постановою Верховної Ради України "Про утворення та ліквідацію районів" від 17 липня 2020 року № 807-IX, але не довше ніж один рік з дня припинення чи скасування воєнного стану на території України, введеного Указом Президента України від 24 лютого 2022 року № 64/2022 "Про введення воєнного стану в Україні", затвердженого Законом України "Про затвердження Указу Президента України "Про введення воєнного стану в Україні" від 24 лютого 2022 року № 2102-IX.\nЗгідно із п. 1 ч. 1 ст. 31 ЦПК України суд передає справу на розгляд іншому суду, якщо справа належить до територіальної юрисдикції (підсудності) іншого суду.\nВраховуючи викладене вважаю, що дану справу належить передати за територіальною юрисдикцією (підсудністю) до Вінницького міського суду Вінницької області.\nКеруючись ст.ст. 27, 31, 260, 353, 355 ЦПК України, суддя,\n\nУХВАЛИВ:\nЦивільну справу № 149/4141/24 за позовом Державної екологічної інспекції у Вінницькій області, третя особа, яка не заявляє самостійних вимог щодо предмета спору на стороні позивача: Уланівська сільська рада Хмільницького району Вінницької області до ОСОБА_1 про відшкодування шкоди, завданої державі внаслідок порушення природоохоронного законодавства, - передати на розгляд за територіальною юрисдикцією (підсудністю) до Вінницького міського суду Вінницької області (вул. Грушевського, 17, м. Вінниця, 21000).\nУхвала суду набирає законної сили з моменту підписання суддею. Ухвала суду може бути оскаржена до Вінницького апеляційного суду протягом п`ятнадцяти днів з дня її складення - 02.01.2025.\nСуддя  \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 Ігор ОЛІЙНИК\n\n\x00',
  '\nСправа № 149/339/25\nПровадження №3/149/286/25 \nНомер рядка звіту 208\nП О С Т А Н О В А\nІМЕНЕМ УКРАЇНИ\n\xa0 \xa0 \xa0 \xa0\n20.02.2025 року \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0м. Хмільник\nСуддя Хмільницького міськрайонного суду Вінницької області Олійник І. В., розглянувши матеріали, що надійшли від ГУ ДПС у Вінницькій області про притягнення \nОСОБА_1 , ІНФОРМАЦІЯ_1 , громадянки України, РНОКПП НОМЕР_1 , заміжньої, яка проживає за адресою: АДРЕСА_1 \nдо адміністративної відповідальності за ч. 1 ст. 163-1 КУпАП, \n\nВ С Т А Н О В И В :\n13.01.2025, під час проведення документальної позапланової виїзної перевірки податкового, валютного та іншого законодавства, контроль за дотриманням якого покладено на контролюючі органи встановлено порушення Хмільницькою міжрайонною Державною лабораторією державної служби України з питань безпечності харчових продуктів та захисту споживачів, головою комісії з реорганізації якої є ОСОБА_1 , ведення податкового обліку, а саме п. 44.1 ст. 44, п. 49.1 ст. 49, п. 184.6 ст. 184, п. 198.6 ст. 198, п. 201.11 ст. 201, пп. 266.2.1 п. 266.2, пп. 266.3.1 п. 266.3 ст. 166, пп. 266.7.5 п. 266.7, пп. 266.8.1 п. 266.8 ст. 266, п. 57.1 ст. 57, п. 287.3 ст. 287, п. 63.3 ст. 63 Податкового кодексу України внаслідок чого донараховано податок на додану вартість у сумі 2553 грн, у тому числі за травень 2024, податок на майно відмінний від земельної ділянки у загальній сумі 60484,16 грн. \nВказані дії ОСОБА_1 кваліфіковано, як адміністративне правопорушення, передбачене ч. 1 ст. 163-1 КУпАП.\nУ суді ОСОБА_1 визнала вину та підтвердила викладені у протоколі обставини.\nСуддя, заслухавши пояснення ОСОБА_1 дослідивши матеріали справи, дійшов висновку, що ОСОБА_1 своїми діями вчинила адміністративне правопорушення, передбачене ч. 1 ст. 163-1 КУпАП, що, окрім її пояснень наданих у суді, підтверджується: протоколом про адміністративне правопорушення № 28 від 13.01.2025; актом перевірки № 558/02-32-07-13/32885289 від 13.01.2025.\nПриймаючи до уваги характер вчиненого правопорушення, особу ОСОБА_1 ,\xa0яка визнала\xa0вину,\xa0раніше до\xa0адміністративної відповідальності\xa0не притягувалася,\xa0має на\xa0утриманні двох\xa0дітей,\xa0суддя дійшов\xa0висновку,\xa0що до\xa0неї належить застосувати адміністративне стягнення у виді штрафу в розмірі п`яти неоподатковуваних мінімумів доходів громадян. \nВідповідно до ст. 40-1 КУпАП, п. 5 ч. 2 ст. 4 Закону України "Про судовий збір" у разі ухвалення судом постанови про накладення адміністративного стягнення, з особи на яку накладено адміністративне стягнення, стягується судовий збір в розмірі 0,2 розміру прожиткового мінімуму для працездатних осіб.\nКеруючись ст.ст.\xa027,\xa033-35,\xa0163-1,\xa0221,\xa0280,\xa0284,\xa0294,\xa0307,\xa0308\xa0КУпАП, суддя, \n\nП О С Т А Н О В И В:\nОСОБА_1 визнати винною у вчиненні адміністративного правопорушення, передбаченого ч. 1 ст. 163-1 КУпАП та застосувати до неї адміністративне стягнення у виді штрафу в дохід держави (Отримувач коштів: ГУК у Він.обл./Хмільн.р-н/21081100, Код отримувача (ЄДРПОУ): 37979858, Банк отримувача: Казначейство України (ЕАП), Номер рахунку (IBAN): UA308999980313060106000002624, Код класифікації доходів бюджету: 21081100) у розмірі п`яти неоподатковуваних мінімумів доходів громадян, що становить 85 грн. \nСтягнути з ОСОБА_1 в дохід держави (Отримувач: ГУК у м. Києві/м.Київ/22030106, Код отримувача (ЄДРПОУ): 37993783, Банк отримувача: Казначейство України (ЕАП), Рахунок отримувача: UA908999980313111256000026001, Код класифікації доходів бюджету: 22030106) судовий збір в розмірі 605,60 грн.\nЗгідно із ч. 1 ст. 307 КУпАП, штраф має бути сплачений порушником не пізніш як через п`ятнадцять днів з дня вручення йому постанови про накладення штрафу, крім випадків, передбачених статтею 300-1 цього Кодексу, а в разі оскарження такої постанови - не пізніш як через п`ятнадцять днів з дня повідомлення про залишення скарги без задоволення. \nВідповідно до ст.\xa0308\xa0КУпАП у разі несплати правопорушником штрафу у строк, установлений частиною першою статті 307 цього Кодексу, постанова про накладення штрафу надсилається для примусового виконання до відділу державної виконавчої служби за місцем проживання порушника, роботи або за місцезнаходженням його майна в порядку, встановленому законом. У порядку примусового виконання постанови про стягнення штрафу за вчинення адміністративного правопорушення з правопорушника стягується: подвійний розмір штрафу, визначеного у відповідній статті цього\xa0Кодексу та зазначеного у постанові про стягнення штрафу; витрати на облік зазначених правопорушень. \nПостанова суду може бути оскаржена до Вінницького апеляційного суду через Хмільницький міськрайонний суд протягом десяти днів з дня її винесення.\n\n\xa0 \xa0 \xa0 \xa0Суддя \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 Ігор ОЛІЙНИК \n\n\n\n\n\n\n\x00',
  '\nСправа № 149/6/25\nПровадження №2/149/219/25 \nНомер рядка звіту 40 \nУ Х В А Л А\nпро відкриття провадження у справі\n14.01.2025 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 м. Хмільник\nСуддя Хмільницького міськрайонного суду Вінницької області Олійник І. В., отримавши позовну заяву ТОВ "ФК "Кредит-Капітал" до ОСОБА_1 про стягнення заборгованості,\nВСТАНОВИВ:\nДо Хмільницького міськрайонного суду Вінницької області надійшла вказана позовна заява,, яка підсудна цьому суду, відповідає вимогам ст.ст. 175-177 ЦПК України, підстави для залишення її без руху, повернення, відмови у відкритті провадження відсутні. \nЗа змістом ст.\xa0274\xa0ЦПК України\xa0дана справа підлягає розгляду в порядку спрощеного позовного провадження.\nВиходячи з\xa0викладеного,\xa0вважаю,\xa0що у\xa0справі слід\xa0відкрити провадження\xa0 тавідповідно до ч. 5 ст. 279 ЦПК України, з власної ініціативи суду, призначити її до розгляду за правилами спрощеного позовного провадження з повідомленням (викликом) сторін.\nНа підставі наведеного, керуючись ст.ст.\xa019,\xa0175,\xa0177,\xa0187,\xa0274,\xa0277\xa0\xa0ЦПК України, суддя, \nУХВАЛИВ:\nПрийняти позовну заяву до розгляду та відкрити провадження за позовом ТОВ "ФК "Кредит-Капітал" до ОСОБА_1 про стягнення заборгованості.\nРозгляд справи здійснюватиметься за правилами спрощеного позовного провадження з повідомленням (викликом) сторін.\nПризначити судове засідання для розгляду справи по суті на\xa010:00 год 27.02.2025 в залі судових засідань Хмільницького міськрайонного суду (22000, Вінницька область, м. Хмільник, вул. Столярчука, 4).\nВизначити відповідачу п`ятнадцятиденний строк з дня вручення даної ухвали для подання відзиву на позовну заяву. У зазначений строк відповідач має право надіслати суду відзив на позовну заяву, який повинен відповідати вимогам ст. 178 ЦПК України, і всі письмові та електронні докази (які можливо доставити до суду), висновки експертів і заяви свідків, що підтверджують заперечення проти позову. Відповідно до вимог ч. 4 ст. 178 ЦПК України, одночасно з надісланням (наданням) відзиву до суду, копія відзиву та доданих до нього документів відповідач зобов`язаний надіслати\xa0 іншим учасникам справи. У разі ненадання відповідачем відзиву у встановлений судом строк без поважних причин суд вирішує справу за наявними матеріалами (ч. 8 ст. 178 ЦПК України). Відповідно до ч. 1 ст. 193 ЦПК України у строк для подання відзиву відповідач має право пред`явити зустрічний позов.\nВстановити позивачу п`ятиденний строк з дня отримання відзиву для подання відповіді на відзив, яка має відповідати вимогам ч.ч. 3-5 ст. 178 ЦПК України, копія якої одночасно з поданням до суду повинна бути надіслана іншим учасникам справи.\nВстановити відповідачу п`ятиденний строк з дня отримання відповіді на відзив для подання заперечення, яке має відповідати вимогам ч.ч. 3-5 ст. 178 ЦПК України, копія якого одночасно з поданням до суду повинна бути надіслана іншим учасникам справи.\nЗа змістом ч. 1 ст. 212 ЦПК України учасники справи мають право брати участь у судовому засіданні в режимі відеоконференції, оскільки в суді наявна відповідна технічна можливість, крім випадків, коли явка учасника справи в судове засідання визнана судом обов`язковою. \nУчасники справи можуть отримати інформацію щодо справи за веб-адресою: https://hm.vn.court.gov.ua/sud0227/. Копію ухвали, копії позовної заяви та доданих документів надіслати учасникам судового розгляду. \nУхвала\xa0оскарженню не підлягає. \n\n\xa0Суддя  \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0Ігор ОЛІЙНИК \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \n\n\x00'],
 'data': None,
 'uris': None,
 'included': ['metadatas', 'documents', 'embeddings']}

In [59]:
q = """Вінницька область, м. Хмільник, вул. Столярчука, 4"""

In [60]:
collection.query(
    query_texts=[q],
    n_results=1
)

{'ids': [['id2']],
 'distances': [[0.5257132]],
 'embeddings': None,
 'metadatas': [[{'source': '149/4141/24'}]],
 'documents': [['\nСправа № 149/4141/24\nПровадження №2/149/196/25 \nНомер рядка звіту 48\n\xa0 У\xa0Х В\xa0А Л\xa0А \n"02" січня 2025 р. \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0м. Хмільник\nСуддя Хмільницького міськрайонного суду Вінницької області Олійник І. В., перевіривши матеріали справи за позовом Державної екологічної інспекції у Вінницькій області, третя особа, яка не заявляє самостійних вимог щодо предмета спору на стороні позивача: Уланівська сільська рада Хмільницького району Вінницької області до ОСОБА_1 про відшкодування шкоди, завданої державі внаслідок порушення природоохоронного законодавства,\n\nВСТАНОВИВ:\nДо Хмільницького міськрайонного суду Вінницької області надійшла вказана позовна заява.\nДослідивши матеріали, суддя дійшов висновку про передачу її за підсудністю, з огляду на наступне.\nЗгідно із ч. 1 ст. 27 ЦПК України позови до фізичної особи пред`являються в суд за зареєстрованим у встановленому законом порядку місцем її проживання або перебування, якщо інше не передбачено законом.\nВідповідно до інформації з Єдиного державного демографічного реєстру № 1004293 від 01.01.2025 встановлено, що відповідач зареєстрована за адресою: АДРЕСА_1 , що належить до територіальної юрисдикції (підсудності) Вінницького міського суду Вінницької області.\nЗгідно із п. 3, п. 3-1 розділу ХІІ "Прикінцеві та перехідні положення" Закону України "Про судоустрій і статус суддів", районні, міжрайонні, районні у містах, міські, міськрайонні суди продовжують здійснювати свої повноваження до утворення та початку діяльності місцевого окружного суду, юрисдикція якого розповсюджується на відповідну територію. До набрання чинності законом України щодо зміни системи місцевих судів на території України у зв`язку з утворенням (ліквідацією) районів відповідні місцеві суди продовжують здійснювати свої повноваження у межах територіальної юрисдикції, визначеної до набрання чинності Постановою Верховної Ради України "Про утворення та ліквідацію районів" від 17 липня 2020 року № 807-IX, але не довше ніж один рік з дня припинення чи скасування воєнного стану на території України, введеного Указом Президента України від 24 лютого 2022 року № 64/2022 "Про введення воєнного стану в Україні", затвердженого Законом України "Про затвердження Указу Президента України "Про введення воєнного стану в Україні" від 24 лютого 2022 року № 2102-IX.\nЗгідно із п. 1 ч. 1 ст. 31 ЦПК України суд передає справу на розгляд іншому суду, якщо справа належить до територіальної юрисдикції (підсудності) іншого суду.\nВраховуючи викладене вважаю, що дану справу належить передати за територіальною юрисдикцією (підсудністю) до Вінницького міського суду Вінницької області.\nКеруючись ст.ст. 27, 31, 260, 353, 355 ЦПК України, суддя,\n\nУХВАЛИВ:\nЦивільну справу № 149/4141/24 за позовом Державної екологічної інспекції у Вінницькій області, третя особа, яка не заявляє самостійних вимог щодо предмета спору на стороні позивача: Уланівська сільська рада Хмільницького району Вінницької області до ОСОБА_1 про відшкодування шкоди, завданої державі внаслідок порушення природоохоронного законодавства, - передати на розгляд за територіальною юрисдикцією (підсудністю) до Вінницького міського суду Вінницької області (вул. Грушевського, 17, м. Вінниця, 21000).\nУхвала суду набирає законної сили з моменту підписання суддею. Ухвала суду може бути оскаржена до Вінницького апеляційного суду протягом п`ятнадцяти днів з дня її складення - 02.01.2025.\nСуддя  \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 Ігор ОЛІЙНИК\n\n\x00']],
 'uris': None,
 'data': None,
 'included': ['metadatas', 'documents', 'distances']}

In [63]:
collection.get(
    where_document={"$contains": "Хмільник"},
    limit=2
)

{'ids': ['id1', 'id2'],
 'embeddings': None,
 'metadatas': [{'source': '149/3813/25'}, {'source': '149/4141/24'}],
 'documents': ['\nУ Х В А Л А\nСправа № 149/3813/25\nПровадження №1-кс/149/687/25\n\n24.11.2025 р. \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 м. Хмільник\nХмільницький міськрайонний суд Вінницької області в складі:\nслідчого судді ОСОБА_1 ,\nза участі секретаря ОСОБА_2 ,\nпрокурора ОСОБА_3 (приймає участь в режимі відеоконференції)\nслідчого ОСОБА_4 ,\nзахисника адвоката ОСОБА_5 ,\nпідозрюваного ОСОБА_6 ,\nрозглянувши у судовому засіданні клопотання слідчої СВ Хмільницького РВП ГУНП у Вінницькій області ОСОБА_7 про застосування запобіжного заходу у вигляді тримання під вартою, заявлене у кримінальному провадженні № 42023052210000216, внесеному до Єдиного реєстру досудових розслідувань 29.05.2023, за ознаками кримінального правопорушення, передбаченого ч. 4\xa0ст. 408 КК України, стосовно\nОСОБА_6 , ІНФОРМАЦІЯ_1 , громадянина України, не одруженого, проживаючого за адресою: АДРЕСА_1 \n\nВСТАНОВИВ:\n24.11.2025 до Хмільницького міськрайонного суду Вінницької області надійшло вказане клопотання, яке мотивовано тим, що ОСОБА_6 обґрунтовано підозрюється у вчиненні кримінального правопорушення, передбаченого ч. 4 ст. 408 КК України, яке, відповідно до\xa0ст. 12 КК України, є особливо тяжким злочином. В ході досудового розслідування встановлено наявність ризиків, передбачених п.п. 1, 3 ч. 1\xa0ст. 177 КПК України, а тому слідча, за погодженням із прокурором, просить застосувати до підозрюваного запобіжний захід у вигляді тримання під вартою строком 60 днів.\nСлідчий та прокурор у судовому засіданні підтримали клопотання.\nЗахисник та підозрюваний у судовому засіданні заперечили проти задоволення клопотання та просили обрати більш м`який запобіжний захід, зокрема у виді домашнього арешту в нічний період доби або заставу, оскільки підозрюваний здійснює догляд за своєю бабусею.\nСлідчий суддя, вислухавши думку учасників процесу, дослідивши матеріали клопотання, дійшов висновку, що клопотання підлягає задоволенню, враховуючи наступне.\n29.05.2023 до ЄРДР за № 42023052210000216 внесено відомості за фактом вчинення ОСОБА_6 кримінального правопорушення, передбаченого ч. 4 ст. 408 КК України.\n21.07.2025 ОСОБА_6 повідомлено про підозру у вчиненні кримінального правопорушення, передбаченого ч. 4 ст. 408 КК України, а 22.11.2025 про зміну раніше повідомленої підозри.\n22.11.2025 о 10:58 год ОСОБА_6 затримано на підставі\xa0ст. 208 КПК України.\nПід час розгляду клопотання про застосування запобіжного заходу встановлено, що надані сторонами кримінального провадження докази доводять обставини, які свідчать про обґрунтовану підозру у вчиненні підозрюваним кримінального правопорушення, передбаченого ч. 4\xa0ст. 408 КК України, що підтверджується: витягом з ЄРДР; документами щодо проходження підозрюваним військової служби, а також наказами про зарахування та відрахування з військових частин, актами службових розслідувань; іншими зібраними доказами.\nІснують ризики, передбачені п.п. 1, 3 ч. 1 ст. 177 КПК України, на які вказує у своєму клопотанні слідча, що полягають у необхідності запобігання спробам підозрюваного переховуватися від органів досудового розслідування та/або суду; незаконно впливати на свідків у цьому ж кримінальному провадженні.\nПри цьому, суд враховує вагомість наявних доказів про вчинення підозрюваним вказаного кримінального правопорушення, тяжкість покарання, що загрожує у разі визнання його винуватим у вчиненні кримінального правопорушення, його вік, стан здоров`я.\nСуд відхиляє доводи сторони захисту про можливість застосування більш м`якого запобіжного заходу, оскільки ч. 8\xa0ст. 176 КПК України\xa0визначено, що під час дії воєнного стану до військовослужбовців, які підозрюються або обвинувачуються у вчиненні злочинів, передбачених статтями\xa0402-405,\xa0407,\xa0408,\xa0429 Кримінального кодексу України, застосовується виключно запобіжний захід, визначений пунктом 5 частини першої цієї статті. Враховуючи те, що на даний час діє воєнний стан, до підозрюваного за\xa0ст. 408 КК України\xa0може бути застосовано лише тримання під вартою. Окрім того, суд враховує, що підозрюваний оголошувався в розшук. \nКримінальне правопорушення, яке інкриміноване ОСОБА_6 , за відомостями слідства вчинено 20.01.2023. Та обставина, що ОСОБА_6 на даний час оформив догляд за бабусею не є підставою для звільнення від кримінальної відповідальності. При цьому, як встановлено з довідок у с. Іванів зареєстровано 11 осіб, які входять до складу його сім`ї. Доказів того, що догляд за бабусею може здійснювати виключно ОСОБА_6 суду не надано.\nЗгідно з п. 4 ч. 2\xa0ст. 183 КПК України\xa0запобіжний захід у вигляді тримання під вартою не може бути застосований, окрім як, зокрема, до раніше не судимої особи, яка підозрюється або обвинувачується у вчиненні злочину, за який законом передбачено покарання у виді позбавлення волі на строк понад п`ять років.\nВраховуючи викладене та приймаючи до уваги встановлені обставини, слідчий суддя доходить висновку про наявність підстав для задоволення клопотання та обрання підозрюваному запобіжного заходу у вигляді тримання під вартою.\nПри цьому, слідчий суддя, у відповідності до абз. 8 ч. 4\xa0ст. 183 КПК України, не вважає необхідне визначати розмір застави, оскільки кримінальне провадження порушено за фактом вчинення злочину, передбаченого\xa0ст. 408 КК України.\nНа підставі вищевикладеного і керуючись ст.ст.\xa0177,\xa0178,\xa0181,\xa0183,\xa0184,\xa0193,\xa0194,\xa0395 КПК України,\n\nУХВАЛИВ:\nКлопотання слідчої СВ Хмільницького РВП ГУНП у Вінницькій області ОСОБА_7 про застосування запобіжного заходу у вигляді тримання під вартою - задовольнити.\nЗастосувати до ОСОБА_6 запобіжний захід у вигляді тримання під вартою строком 60 днів, тобто до 10:58 год 20.01.2026.\nСтрок тримання ОСОБА_6 під вартою рахувати з моменту затримання, тобто 10:58 год 22.11.2025.\nУхвала слідчого судді підлягає негайному виконанню після її проголошення.\nУхвала слідчого судді може бути оскаржена до Вінницького апеляційного суду протягом 5 днів з дня її оголошення, однак оскарження ухвали не зупиняє її виконання.\n\nСлідчий суддя\xa0\xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0\xa0 ОСОБА_8 \n\n\n\n\n\n\n\x00',
  '\nСправа № 149/4141/24\nПровадження №2/149/196/25 \nНомер рядка звіту 48\n\xa0 У\xa0Х В\xa0А Л\xa0А \n"02" січня 2025 р. \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0м. Хмільник\nСуддя Хмільницького міськрайонного суду Вінницької області Олійник І. В., перевіривши матеріали справи за позовом Державної екологічної інспекції у Вінницькій області, третя особа, яка не заявляє самостійних вимог щодо предмета спору на стороні позивача: Уланівська сільська рада Хмільницького району Вінницької області до ОСОБА_1 про відшкодування шкоди, завданої державі внаслідок порушення природоохоронного законодавства,\n\nВСТАНОВИВ:\nДо Хмільницького міськрайонного суду Вінницької області надійшла вказана позовна заява.\nДослідивши матеріали, суддя дійшов висновку про передачу її за підсудністю, з огляду на наступне.\nЗгідно із ч. 1 ст. 27 ЦПК України позови до фізичної особи пред`являються в суд за зареєстрованим у встановленому законом порядку місцем її проживання або перебування, якщо інше не передбачено законом.\nВідповідно до інформації з Єдиного державного демографічного реєстру № 1004293 від 01.01.2025 встановлено, що відповідач зареєстрована за адресою: АДРЕСА_1 , що належить до територіальної юрисдикції (підсудності) Вінницького міського суду Вінницької області.\nЗгідно із п. 3, п. 3-1 розділу ХІІ "Прикінцеві та перехідні положення" Закону України "Про судоустрій і статус суддів", районні, міжрайонні, районні у містах, міські, міськрайонні суди продовжують здійснювати свої повноваження до утворення та початку діяльності місцевого окружного суду, юрисдикція якого розповсюджується на відповідну територію. До набрання чинності законом України щодо зміни системи місцевих судів на території України у зв`язку з утворенням (ліквідацією) районів відповідні місцеві суди продовжують здійснювати свої повноваження у межах територіальної юрисдикції, визначеної до набрання чинності Постановою Верховної Ради України "Про утворення та ліквідацію районів" від 17 липня 2020 року № 807-IX, але не довше ніж один рік з дня припинення чи скасування воєнного стану на території України, введеного Указом Президента України від 24 лютого 2022 року № 64/2022 "Про введення воєнного стану в Україні", затвердженого Законом України "Про затвердження Указу Президента України "Про введення воєнного стану в Україні" від 24 лютого 2022 року № 2102-IX.\nЗгідно із п. 1 ч. 1 ст. 31 ЦПК України суд передає справу на розгляд іншому суду, якщо справа належить до територіальної юрисдикції (підсудності) іншого суду.\nВраховуючи викладене вважаю, що дану справу належить передати за територіальною юрисдикцією (підсудністю) до Вінницького міського суду Вінницької області.\nКеруючись ст.ст. 27, 31, 260, 353, 355 ЦПК України, суддя,\n\nУХВАЛИВ:\nЦивільну справу № 149/4141/24 за позовом Державної екологічної інспекції у Вінницькій області, третя особа, яка не заявляє самостійних вимог щодо предмета спору на стороні позивача: Уланівська сільська рада Хмільницького району Вінницької області до ОСОБА_1 про відшкодування шкоди, завданої державі внаслідок порушення природоохоронного законодавства, - передати на розгляд за територіальною юрисдикцією (підсудністю) до Вінницького міського суду Вінницької області (вул. Грушевського, 17, м. Вінниця, 21000).\nУхвала суду набирає законної сили з моменту підписання суддею. Ухвала суду може бути оскаржена до Вінницького апеляційного суду протягом п`ятнадцяти днів з дня її складення - 02.01.2025.\nСуддя  \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 Ігор ОЛІЙНИК\n\n\x00'],
 'data': None,
 'uris': None,
 'included': ['metadatas', 'documents']}

4

In [8]:
print(clean_legal_text(rtf_texts[0]))

УХВАЛА
Справа No 149/3813/25
Провадження No1-кс/149/687/25

24.11.2025 р. м. Хмільник
Хмільницький міськрайонний суд Вінницької області в складі:
слідчого судді ОСОБА_1 ,
за участі секретаря ОСОБА_2 ,
прокурора ОСОБА_3 (приймає участь в режимі відеоконференції)
слідчого ОСОБА_4 ,
захисника адвоката ОСОБА_5 ,
підозрюваного ОСОБА_6 ,
розглянувши у судовому засіданні клопотання слідчої СВ Хмільницького РВП ГУНП у Вінницькій області ОСОБА_7 про застосування запобіжного заходу у вигляді тримання під вартою, заявлене у кримінальному провадженні No 42023052210000216, внесеному до Єдиного реєстру досудових розслідувань 29.05.2023, за ознаками кримінального правопорушення, передбаченого ч. 4 ст. 408 КК України, стосовно
ОСОБА_6 , ІНФОРМАЦІЯ_1 , громадянина України, не одруженого, проживаючого за адресою: АДРЕСА_1

ВСТАНОВИВ:
24.11.2025 до Хмільницького міськрайонного суду Вінницької області надійшло вказане клопотання, яке мотивовано тим, що ОСОБА_6 обґрунтовано підозрюється у вчиненні кримінального правопорушення, передбаченого ч. 4 ст. 408 КК України, яке, відповідно до ст. 12 КК України, є особливо тяжким злочином. В ході досудового розслідування встановлено наявність ризиків, передбачених п.п. 1, 3 ч. 1 ст. 177 КПК України, а тому слідча, за погодженням із прокурором, просить застосувати до підозрюваного запобіжний захід у вигляді тримання під вартою строком 60 днів.
Слідчий та прокурор у судовому засіданні підтримали клопотання.
Захисник та підозрюваний у судовому засіданні заперечили проти задоволення клопотання та просили обрати більш м`який запобіжний захід, зокрема у виді домашнього арешту в нічний період доби або заставу, оскільки підозрюваний здійснює догляд за своєю бабусею.
Слідчий суддя, вислухавши думку учасників процесу, дослідивши матеріали клопотання, дійшов висновку, що клопотання підлягає задоволенню, враховуючи наступне.
29.05.2023 до ЄРДР за No 42023052210000216 внесено відомості за фактом вчинення ОСОБА_6 кримінального правопорушення, передбаченого ч. 4 ст. 408 КК України.
21.07.2025 ОСОБА_6 повідомлено про підозру у вчиненні кримінального правопорушення, передбаченого ч. 4 ст. 408 КК України, а 22.11.2025 про зміну раніше повідомленої підозри.
22.11.2025 о 10:58 год ОСОБА_6 затримано на підставі ст. 208 КПК України.
Під час розгляду клопотання про застосування запобіжного заходу встановлено, що надані сторонами кримінального провадження докази доводять обставини, які свідчать про обґрунтовану підозру у вчиненні підозрюваним кримінального правопорушення, передбаченого ч. 4 ст. 408 КК України, що підтверджується: витягом з ЄРДР; документами щодо проходження підозрюваним військової служби, а також наказами про зарахування та відрахування з військових частин, актами службових розслідувань; іншими зібраними доказами.
Існують ризики, передбачені п.п. 1, 3 ч. 1 ст. 177 КПК України, на які вказує у своєму клопотанні слідча, що полягають у необхідності запобігання спробам підозрюваного переховуватися від органів досудового розслідування та/або суду; незаконно впливати на свідків у цьому ж кримінальному провадженні.
При цьому, суд враховує вагомість наявних доказів про вчинення підозрюваним вказаного кримінального правопорушення, тяжкість покарання, що загрожує у разі визнання його винуватим у вчиненні кримінального правопорушення, його вік, стан здоров`я.
Суд відхиляє доводи сторони захисту про можливість застосування більш м`якого запобіжного заходу, оскільки ч. 8 ст. 176 КПК України визначено, що під час дії воєнного стану до військовослужбовців, які підозрюються або обвинувачуються у вчиненні злочинів, передбачених статтями 402-405, 407, 408, 429 Кримінального кодексу України, застосовується виключно запобіжний захід, визначений пунктом 5 частини першої цієї статті. Враховуючи те, що на даний час діє воєнний стан, до підозрюваного за ст. 408 КК України може бути застосовано лише тримання під вартою. Окрім того, суд враховує, що підозрюваний оголошувався в розшук.
Кримінальне правопорушення, яке інкриміноване ОСОБА_6 , за відомостями слідства вчинено 20.01.2023. Та обставина, що ОСОБА_6 на даний час оформив догляд за бабусею не є підставою для звільнення від кримінальної відповідальності. При цьому, як встановлено з довідок у с. Іванів зареєстровано 11 осіб, які входять до складу його сім`ї. Доказів того, що догляд за бабусею може здійснювати виключно ОСОБА_6 суду не надано.
Згідно з п. 4 ч. 2 ст. 183 КПК України запобіжний захід у вигляді тримання під вартою не може бути застосований, окрім як, зокрема, до раніше не судимої особи, яка підозрюється або обвинувачується у вчиненні злочину, за який законом передбачено покарання у виді позбавлення волі на строк понад п`ять років.
Враховуючи викладене та приймаючи до уваги встановлені обставини, слідчий суддя доходить висновку про наявність підстав для задоволення клопотання та обрання підозрюваному запобіжного заходу у вигляді тримання під вартою.
При цьому, слідчий суддя, у відповідності до абз. 8 ч. 4 ст. 183 КПК України, не вважає необхідне визначати розмір застави, оскільки кримінальне провадження порушено за фактом вчинення злочину, передбаченого ст. 408 КК України.
На підставі вищевикладеного і керуючись ст.ст. 177, 178, 181, 183, 184, 193, 194, 395 КПК України,

УХВАЛИВ:
Клопотання слідчої СВ Хмільницького РВП ГУНП у Вінницькій області ОСОБА_7 про застосування запобіжного заходу у вигляді тримання під вартою - задовольнити.
Застосувати до ОСОБА_6 запобіжний захід у вигляді тримання під вартою строком 60 днів, тобто до 10:58 год 20.01.2026.
Строк тримання ОСОБА_6 під вартою рахувати з моменту затримання, тобто 10:58 год 22.11.2025.
Ухвала слідчого судді підлягає негайному виконанню після її проголошення.
Ухвала слідчого судді може бути оскаржена до Вінницького апеляційного суду протягом 5 днів з дня її оголошення, однак оскарження ухвали не зупиняє її виконання.

Слідчий суддя ОСОБА_8

 

In [7]:
print(rtf_texts[0])

У Х В А Л А
Справа № 149/3813/25
Провадження №1-кс/149/687/25

24.11.2025 р.                                                                 м. Хмільник
Хмільницький міськрайонний суд Вінницької області в складі:
слідчого судді ОСОБА_1 ,
за участі секретаря ОСОБА_2 ,
прокурора ОСОБА_3 (приймає участь в режимі відеоконференції)
слідчого ОСОБА_4 ,
захисника адвоката ОСОБА_5 ,
підозрюваного ОСОБА_6 ,
розглянувши у судовому засіданні клопотання слідчої СВ Хмільницького РВП ГУНП у Вінницькій області ОСОБА_7 про застосування запобіжного заходу у вигляді тримання під вартою, заявлене у кримінальному провадженні № 42023052210000216, внесеному до Єдиного реєстру досудових розслідувань 29.05.2023, за ознаками кримінального правопорушення, передбаченого ч. 4 ст. 408 КК України, стосовно
ОСОБА_6 , ІНФОРМАЦІЯ_1 , громадянина України, не одруженого, проживаючого за адресою: АДРЕСА_1

ВСТАНОВИВ:
24.11.2025 до Хмільницького міськрайонного суду Вінницької області надійшло вказане клопотання, яке мотивовано тим, що ОСОБА_6 обґрунтовано підозрюється у вчиненні кримінального правопорушення, передбаченого ч. 4 ст. 408 КК України, яке, відповідно до ст. 12 КК України, є особливо тяжким злочином. В ході досудового розслідування встановлено наявність ризиків, передбачених п.п. 1, 3 ч. 1 ст. 177 КПК України, а тому слідча, за погодженням із прокурором, просить застосувати до підозрюваного запобіжний захід у вигляді тримання під вартою строком 60 днів.
Слідчий та прокурор у судовому засіданні підтримали клопотання.
Захисник та підозрюваний у судовому засіданні заперечили проти задоволення клопотання та просили обрати більш м`який запобіжний захід, зокрема у виді домашнього арешту в нічний період доби або заставу, оскільки підозрюваний здійснює догляд за своєю бабусею.
Слідчий суддя, вислухавши думку учасників процесу, дослідивши матеріали клопотання, дійшов висновку, що клопотання підлягає задоволенню, враховуючи наступне.
29.05.2023 до ЄРДР за № 42023052210000216 внесено відомості за фактом вчинення ОСОБА_6 кримінального правопорушення, передбаченого ч. 4 ст. 408 КК України.
21.07.2025 ОСОБА_6 повідомлено про підозру у вчиненні кримінального правопорушення, передбаченого ч. 4 ст. 408 КК України, а 22.11.2025 про зміну раніше повідомленої підозри.
22.11.2025 о 10:58 год ОСОБА_6 затримано на підставі ст. 208 КПК України.
Під час розгляду клопотання про застосування запобіжного заходу встановлено, що надані сторонами кримінального провадження докази доводять обставини, які свідчать про обґрунтовану підозру у вчиненні підозрюваним кримінального правопорушення, передбаченого ч. 4 ст. 408 КК України, що підтверджується: витягом з ЄРДР; документами щодо проходження підозрюваним військової служби, а також наказами про зарахування та відрахування з військових частин, актами службових розслідувань; іншими зібраними доказами.
Існують ризики, передбачені п.п. 1, 3 ч. 1 ст. 177 КПК України, на які вказує у своєму клопотанні слідча, що полягають у необхідності запобігання спробам підозрюваного переховуватися від органів досудового розслідування та/або суду; незаконно впливати на свідків у цьому ж кримінальному провадженні.
При цьому, суд враховує вагомість наявних доказів про вчинення підозрюваним вказаного кримінального правопорушення, тяжкість покарання, що загрожує у разі визнання його винуватим у вчиненні кримінального правопорушення, його вік, стан здоров`я.
Суд відхиляє доводи сторони захисту про можливість застосування більш м`якого запобіжного заходу, оскільки ч. 8 ст. 176 КПК України визначено, що під час дії воєнного стану до військовослужбовців, які підозрюються або обвинувачуються у вчиненні злочинів, передбачених статтями 402-405, 407, 408, 429 Кримінального кодексу України, застосовується виключно запобіжний захід, визначений пунктом 5 частини першої цієї статті. Враховуючи те, що на даний час діє воєнний стан, до підозрюваного за ст. 408 КК України може бути застосовано лише тримання під вартою. Окрім того, суд враховує, що підозрюваний оголошувався в розшук.
Кримінальне правопорушення, яке інкриміноване ОСОБА_6 , за відомостями слідства вчинено 20.01.2023. Та обставина, що ОСОБА_6 на даний час оформив догляд за бабусею не є підставою для звільнення від кримінальної відповідальності. При цьому, як встановлено з довідок у с. Іванів зареєстровано 11 осіб, які входять до складу його сім`ї. Доказів того, що догляд за бабусею може здійснювати виключно ОСОБА_6 суду не надано.
Згідно з п. 4 ч. 2 ст. 183 КПК України запобіжний захід у вигляді тримання під вартою не може бути застосований, окрім як, зокрема, до раніше не судимої особи, яка підозрюється або обвинувачується у вчиненні злочину, за який законом передбачено покарання у виді позбавлення волі на строк понад п`ять років.
Враховуючи викладене та приймаючи до уваги встановлені обставини, слідчий суддя доходить висновку про наявність підстав для задоволення клопотання та обрання підозрюваному запобіжного заходу у вигляді тримання під вартою.
При цьому, слідчий суддя, у відповідності до абз. 8 ч. 4 ст. 183 КПК України, не вважає необхідне визначати розмір застави, оскільки кримінальне провадження порушено за фактом вчинення злочину, передбаченого ст. 408 КК України.
На підставі вищевикладеного і керуючись ст.ст. 177, 178, 181, 183, 184, 193, 194, 395 КПК України,

УХВАЛИВ:
Клопотання слідчої СВ Хмільницького РВП ГУНП у Вінницькій області ОСОБА_7 про застосування запобіжного заходу у вигляді тримання під вартою - задовольнити.
Застосувати до ОСОБА_6 запобіжний захід у вигляді тримання під вартою строком 60 днів, тобто до 10:58 год 20.01.2026.
Строк тримання ОСОБА_6 під вартою рахувати з моменту затримання, тобто 10:58 год 22.11.2025.
Ухвала слідчого судді підлягає негайному виконанню після її проголошення.
Ухвала слідчого судді може бути оскаржена до Вінницького апеляційного суду протягом 5 днів з дня її оголошення, однак оскарження ухвали не зупиняє її виконання.

Слідчий суддя                                                    ОСОБА_8






 

{'ids': [['id3']],
 'distances': [[0.7251667]],
 'embeddings': None,
 'metadatas': [[{'source': '149/339/25'}]],
 'documents': [['\nСправа № 149/339/25\nПровадження №3/149/286/25 \nНомер рядка звіту 208\nП О С Т А Н О В А\nІМЕНЕМ УКРАЇНИ\n\xa0 \xa0 \xa0 \xa0\n20.02.2025 року \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0м. Хмільник\nСуддя Хмільницького міськрайонного суду Вінницької області Олійник І. В., розглянувши матеріали, що надійшли від ГУ ДПС у Вінницькій області про притягнення \nОСОБА_1 , ІНФОРМАЦІЯ_1 , громадянки України, РНОКПП НОМЕР_1 , заміжньої, яка проживає за адресою: АДРЕСА_1 \nдо адміністративної відповідальності за ч. 1 ст. 163-1 КУпАП, \n\nВ С Т А Н О В И В :\n13.01.2025, під час проведення документальної позапланової виїзної перевірки податкового, валютного та іншого законодавства, контроль за дотриманням якого покладено на контролюючі органи встановлено порушення Хмільницькою міжрайонною Державною лабораторією державної служби України з питань безпечності харчових продуктів та захисту споживачів, головою комісії з реорганізації якої є ОСОБА_1 , ведення податкового обліку, а саме п. 44.1 ст. 44, п. 49.1 ст. 49, п. 184.6 ст. 184, п. 198.6 ст. 198, п. 201.11 ст. 201, пп. 266.2.1 п. 266.2, пп. 266.3.1 п. 266.3 ст. 166, пп. 266.7.5 п. 266.7, пп. 266.8.1 п. 266.8 ст. 266, п. 57.1 ст. 57, п. 287.3 ст. 287, п. 63.3 ст. 63 Податкового кодексу України внаслідок чого донараховано податок на додану вартість у сумі 2553 грн, у тому числі за травень 2024, податок на майно відмінний від земельної ділянки у загальній сумі 60484,16 грн. \nВказані дії ОСОБА_1 кваліфіковано, як адміністративне правопорушення, передбачене ч. 1 ст. 163-1 КУпАП.\nУ суді ОСОБА_1 визнала вину та підтвердила викладені у протоколі обставини.\nСуддя, заслухавши пояснення ОСОБА_1 дослідивши матеріали справи, дійшов висновку, що ОСОБА_1 своїми діями вчинила адміністративне правопорушення, передбачене ч. 1 ст. 163-1 КУпАП, що, окрім її пояснень наданих у суді, підтверджується: протоколом про адміністративне правопорушення № 28 від 13.01.2025; актом перевірки № 558/02-32-07-13/32885289 від 13.01.2025.\nПриймаючи до уваги характер вчиненого правопорушення, особу ОСОБА_1 ,\xa0яка визнала\xa0вину,\xa0раніше до\xa0адміністративної відповідальності\xa0не притягувалася,\xa0має на\xa0утриманні двох\xa0дітей,\xa0суддя дійшов\xa0висновку,\xa0що до\xa0неї належить застосувати адміністративне стягнення у виді штрафу в розмірі п`яти неоподатковуваних мінімумів доходів громадян. \nВідповідно до ст. 40-1 КУпАП, п. 5 ч. 2 ст. 4 Закону України "Про судовий збір" у разі ухвалення судом постанови про накладення адміністративного стягнення, з особи на яку накладено адміністративне стягнення, стягується судовий збір в розмірі 0,2 розміру прожиткового мінімуму для працездатних осіб.\nКеруючись ст.ст.\xa027,\xa033-35,\xa0163-1,\xa0221,\xa0280,\xa0284,\xa0294,\xa0307,\xa0308\xa0КУпАП, суддя, \n\nП О С Т А Н О В И В:\nОСОБА_1 визнати винною у вчиненні адміністративного правопорушення, передбаченого ч. 1 ст. 163-1 КУпАП та застосувати до неї адміністративне стягнення у виді штрафу в дохід держави (Отримувач коштів: ГУК у Він.обл./Хмільн.р-н/21081100, Код отримувача (ЄДРПОУ): 37979858, Банк отримувача: Казначейство України (ЕАП), Номер рахунку (IBAN): UA308999980313060106000002624, Код класифікації доходів бюджету: 21081100) у розмірі п`яти неоподатковуваних мінімумів доходів громадян, що становить 85 грн. \nСтягнути з ОСОБА_1 в дохід держави (Отримувач: ГУК у м. Києві/м.Київ/22030106, Код отримувача (ЄДРПОУ): 37993783, Банк отримувача: Казначейство України (ЕАП), Рахунок отримувача: UA908999980313111256000026001, Код класифікації доходів бюджету: 22030106) судовий збір в розмірі 605,60 грн.\nЗгідно із ч. 1 ст. 307 КУпАП, штраф має бути сплачений порушником не пізніш як через п`ятнадцять днів з дня вручення йому постанови про накладення штрафу, крім випадків, передбачених статтею 300-1 цього Кодексу, а в разі оскарження такої постанови - не пізніш як через п`ятнадцять днів з дня повідомлення про залишення скарги без задоволення. \nВідповідно до ст.\xa0308\xa0КУпАП у разі несплати правопорушником штрафу у строк, установлений частиною першою статті 307 цього Кодексу, постанова про накладення штрафу надсилається для примусового виконання до відділу державної виконавчої служби за місцем проживання порушника, роботи або за місцезнаходженням його майна в порядку, встановленому законом. У порядку примусового виконання постанови про стягнення штрафу за вчинення адміністративного правопорушення з правопорушника стягується: подвійний розмір штрафу, визначеного у відповідній статті цього\xa0Кодексу та зазначеного у постанові про стягнення штрафу; витрати на облік зазначених правопорушень. \nПостанова суду може бути оскаржена до Вінницького апеляційного суду через Хмільницький міськрайонний суд протягом десяти днів з дня її винесення.\n\n\xa0 \xa0 \xa0 \xa0Суддя \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 Ігор ОЛІЙНИК \n\n\n\n\n\n\n\x00']],
 'uris': None,
 'data': None,
 'included': ['metadatas', 'documents', 'distances']}

In [29]:
collection.add(
    documents = [rtf_texts[0], rtf_texts[1], rtf_texts[2], rtf_texts[3]],
    metadatas = [{"source": "149/3813/25"},{"source": "149/4141/24"},{'source':'149/339/25'},{'source':'149/6/25'}],
    ids = ["id1", "id2", "id3", "id4"]
)

In [67]:
print(rtf_texts[0])

У Х В А Л А
Справа № 149/3813/25
Провадження №1-кс/149/687/25

24.11.2025 р.                                                                 м. Хмільник
Хмільницький міськрайонний суд Вінницької області в складі:
слідчого судді ОСОБА_1 ,
за участі секретаря ОСОБА_2 ,
прокурора ОСОБА_3 (приймає участь в режимі відеоконференції)
слідчого ОСОБА_4 ,
захисника адвоката ОСОБА_5 ,
підозрюваного ОСОБА_6 ,
розглянувши у судовому засіданні клопотання слідчої СВ Хмільницького РВП ГУНП у Вінницькій області ОСОБА_7 про застосування запобіжного заходу у вигляді тримання під вартою, заявлене у кримінальному провадженні № 42023052210000216, внесеному до Єдиного реєстру досудових розслідувань 29.05.2023, за ознаками кримінального правопорушення, передбаченого ч. 4 ст. 408 КК України, стосовно
ОСОБА_6 , ІНФОРМАЦІЯ_1 , громадянина України, не одруженого, проживаючого за адресою: АДРЕСА_1

ВСТАНОВИВ:
24.11.2025 до Хмільницького міськрайонного суду Вінницької області надійшло вказане клопотання, яке мотивовано тим, що ОСОБА_6 обґрунтовано підозрюється у вчиненні кримінального правопорушення, передбаченого ч. 4 ст. 408 КК України, яке, відповідно до ст. 12 КК України, є особливо тяжким злочином. В ході досудового розслідування встановлено наявність ризиків, передбачених п.п. 1, 3 ч. 1 ст. 177 КПК України, а тому слідча, за погодженням із прокурором, просить застосувати до підозрюваного запобіжний захід у вигляді тримання під вартою строком 60 днів.
Слідчий та прокурор у судовому засіданні підтримали клопотання.
Захисник та підозрюваний у судовому засіданні заперечили проти задоволення клопотання та просили обрати більш м`який запобіжний захід, зокрема у виді домашнього арешту в нічний період доби або заставу, оскільки підозрюваний здійснює догляд за своєю бабусею.
Слідчий суддя, вислухавши думку учасників процесу, дослідивши матеріали клопотання, дійшов висновку, що клопотання підлягає задоволенню, враховуючи наступне.
29.05.2023 до ЄРДР за № 42023052210000216 внесено відомості за фактом вчинення ОСОБА_6 кримінального правопорушення, передбаченого ч. 4 ст. 408 КК України.
21.07.2025 ОСОБА_6 повідомлено про підозру у вчиненні кримінального правопорушення, передбаченого ч. 4 ст. 408 КК України, а 22.11.2025 про зміну раніше повідомленої підозри.
22.11.2025 о 10:58 год ОСОБА_6 затримано на підставі ст. 208 КПК України.
Під час розгляду клопотання про застосування запобіжного заходу встановлено, що надані сторонами кримінального провадження докази доводять обставини, які свідчать про обґрунтовану підозру у вчиненні підозрюваним кримінального правопорушення, передбаченого ч. 4 ст. 408 КК України, що підтверджується: витягом з ЄРДР; документами щодо проходження підозрюваним військової служби, а також наказами про зарахування та відрахування з військових частин, актами службових розслідувань; іншими зібраними доказами.
Існують ризики, передбачені п.п. 1, 3 ч. 1 ст. 177 КПК України, на які вказує у своєму клопотанні слідча, що полягають у необхідності запобігання спробам підозрюваного переховуватися від органів досудового розслідування та/або суду; незаконно впливати на свідків у цьому ж кримінальному провадженні.
При цьому, суд враховує вагомість наявних доказів про вчинення підозрюваним вказаного кримінального правопорушення, тяжкість покарання, що загрожує у разі визнання його винуватим у вчиненні кримінального правопорушення, його вік, стан здоров`я.
Суд відхиляє доводи сторони захисту про можливість застосування більш м`якого запобіжного заходу, оскільки ч. 8 ст. 176 КПК України визначено, що під час дії воєнного стану до військовослужбовців, які підозрюються або обвинувачуються у вчиненні злочинів, передбачених статтями 402-405, 407, 408, 429 Кримінального кодексу України, застосовується виключно запобіжний захід, визначений пунктом 5 частини першої цієї статті. Враховуючи те, що на даний час діє воєнний стан, до підозрюваного за ст. 408 КК України може бути застосовано лише тримання під вартою. Окрім того, суд враховує, що підозрюваний оголошувався в розшук.
Кримінальне правопорушення, яке інкриміноване ОСОБА_6 , за відомостями слідства вчинено 20.01.2023. Та обставина, що ОСОБА_6 на даний час оформив догляд за бабусею не є підставою для звільнення від кримінальної відповідальності. При цьому, як встановлено з довідок у с. Іванів зареєстровано 11 осіб, які входять до складу його сім`ї. Доказів того, що догляд за бабусею може здійснювати виключно ОСОБА_6 суду не надано.
Згідно з п. 4 ч. 2 ст. 183 КПК України запобіжний захід у вигляді тримання під вартою не може бути застосований, окрім як, зокрема, до раніше не судимої особи, яка підозрюється або обвинувачується у вчиненні злочину, за який законом передбачено покарання у виді позбавлення волі на строк понад п`ять років.
Враховуючи викладене та приймаючи до уваги встановлені обставини, слідчий суддя доходить висновку про наявність підстав для задоволення клопотання та обрання підозрюваному запобіжного заходу у вигляді тримання під вартою.
При цьому, слідчий суддя, у відповідності до абз. 8 ч. 4 ст. 183 КПК України, не вважає необхідне визначати розмір застави, оскільки кримінальне провадження порушено за фактом вчинення злочину, передбаченого ст. 408 КК України.
На підставі вищевикладеного і керуючись ст.ст. 177, 178, 181, 183, 184, 193, 194, 395 КПК України,

УХВАЛИВ:
Клопотання слідчої СВ Хмільницького РВП ГУНП у Вінницькій області ОСОБА_7 про застосування запобіжного заходу у вигляді тримання під вартою - задовольнити.
Застосувати до ОСОБА_6 запобіжний захід у вигляді тримання під вартою строком 60 днів, тобто до 10:58 год 20.01.2026.
Строк тримання ОСОБА_6 під вартою рахувати з моменту затримання, тобто 10:58 год 22.11.2025.
Ухвала слідчого судді підлягає негайному виконанню після її проголошення.
Ухвала слідчого судді може бути оскаржена до Вінницького апеляційного суду протягом 5 днів з дня її оголошення, однак оскарження ухвали не зупиняє її виконання.

Слідчий суддя                                                    ОСОБА_8






 

In [75]:
collection.similarity_search(query='№ 149/3813/25',k=2)

AttributeError: 'Collection' object has no attribute 'similarity_search'

In [73]:
collection.query(
  query_texts=["Справа № 149/3813/25"],
  n_results=1,
  where_document={"$contains": "search string"}
)

{'ids': [[]],
 'distances': [[]],
 'embeddings': None,
 'metadatas': [[]],
 'documents': [[]],
 'uris': None,
 'data': None,
 'included': ['metadatas', 'documents', 'distances']}

In [57]:
collection.query(
    query_embeddings=[[11.1, 12.1, 13.1]],
    n_results=5
)

InvalidArgumentError: Collection expecting embedding with dimension of 1536, got 3

In [49]:
collection.query(
    query_texts=["судова справа"],
    where={"city": "Хмільник"},
    n_results=10
)

{'ids': [[]],
 'distances': [[]],
 'embeddings': None,
 'metadatas': [[]],
 'documents': [[]],
 'uris': None,
 'data': None,
 'included': ['metadatas', 'documents', 'distances']}

In [44]:
from chromadb import Search, K, Knn, Rrf

In [46]:
# Dense semantic embeddings
dense_rank = Knn(
    query="machine learning research",  # Text query for dense embeddings
    key="#embedding",          # Default embedding field
    return_rank=True,
    limit=200                  # Consider top 200 candidates
)

# Sparse keyword embeddings
sparse_rank = Knn(
    query="machine learning research",  # Text query for sparse embeddings
    key="sparse_embedding",    # Metadata field for sparse vectors
    return_rank=True,
    limit=200
)

# Combine with RRF
hybrid_rank = Rrf(
    ranks=[dense_rank, sparse_rank],
    weights=[0.7, 0.3],       # 70% semantic, 30% keyword
    k=60
)

collection.search("справи із міста Хмільник")

AttributeError: 'str' object has no attribute 'to_dict'

In [2]:
from langchain_chroma import Chroma
from langchain_openai import OpenAIEmbeddings

embeddings = OpenAIEmbeddings(model="text-embedding-3-large")

In [3]:
from langchain_chroma import Chroma

vector_store = Chroma(
    collection_name="example_collection",
    embedding_function=embeddings,
    host="localhost",
)

In [ ]:
collection.add(
    documents = [rtf_texts[0], rtf_texts[1], rtf_texts[2], rtf_texts[3]],
    metadatas = [{"source": "149/3813/25"},{"source": "149/4141/24"},{'source':'149/339/25'},{'source':'149/6/25'}],
    ids = ["id1", "id2", "id3", "id4"]
)

In [ ]:
dfsdf

'\nУ Х В А Л А\nСправа № 149/3813/25\nПровадження №1-кс/149/687/25\n\n24.11.2025 р. \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 м. Хмільник\nХмільницький міськрайонний суд Вінницької області в складі:\nслідчого судді ОСОБА_1 ,\nза участі секретаря ОСОБА_2 ,\nпрокурора ОСОБА_3 (приймає участь в режимі відеоконференції)\nслідчого ОСОБА_4 ,\nзахисника адвоката ОСОБА_5 ,\nпідозрюваного ОСОБА_6 ,\nрозглянувши у судовому засіданні клопотання слідчої СВ Хмільницького РВП ГУНП у Вінницькій області ОСОБА_7 про застосування запобіжного заходу у вигляді тримання під вартою, заявлене у кримінальному провадженні № 42023052210000216, внесеному до Єдиного реєстру досудових розслідувань 29.05.2023, за ознаками кримінального правопорушення, передбаченого ч. 4\xa0ст. 408 КК України, стосовно\nОСОБА_6 , ІНФОРМАЦІЯ_1 , громадянина України, не одруженого, проживаючого за адресою: АДРЕСА_1 \n\nВСТАНОВИВ:\n24.11.2025 до Хмільницького міськрайонного суду Вінницької області надійшло вказане клопотання, яке мотивовано тим, що ОСОБА_6 обґрунтовано підозрюється у вчиненні кримінального правопорушення, передбаченого ч. 4 ст. 408 КК України, яке, відповідно до\xa0ст. 12 КК України, є особливо тяжким злочином. В ході досудового розслідування встановлено наявність ризиків, передбачених п.п. 1, 3 ч. 1\xa0ст. 177 КПК України, а тому слідча, за погодженням із прокурором, просить застосувати до підозрюваного запобіжний захід у вигляді тримання під вартою строком 60 днів.\nСлідчий та прокурор у судовому засіданні підтримали клопотання.\nЗахисник та підозрюваний у судовому засіданні заперечили проти задоволення клопотання та просили обрати більш м`який запобіжний захід, зокрема у виді домашнього арешту в нічний період доби або заставу, оскільки підозрюваний здійснює догляд за своєю бабусею.\nСлідчий суддя, вислухавши думку учасників процесу, дослідивши матеріали клопотання, дійшов висновку, що клопотання підлягає задоволенню, враховуючи наступне.\n29.05.2023 до ЄРДР за № 42023052210000216 внесено відомості за фактом вчинення ОСОБА_6 кримінального правопорушення, передбаченого ч. 4 ст. 408 КК України.\n21.07.2025 ОСОБА_6 повідомлено про підозру у вчиненні кримінального правопорушення, передбаченого ч. 4 ст. 408 КК України, а 22.11.2025 про зміну раніше повідомленої підозри.\n22.11.2025 о 10:58 год ОСОБА_6 затримано на підставі\xa0ст. 208 КПК України.\nПід час розгляду клопотання про застосування запобіжного заходу встановлено, що надані сторонами кримінального провадження докази доводять обставини, які свідчать про обґрунтовану підозру у вчиненні підозрюваним кримінального правопорушення, передбаченого ч. 4\xa0ст. 408 КК України, що підтверджується: витягом з ЄРДР; документами щодо проходження підозрюваним військової служби, а також наказами про зарахування та відрахування з військових частин, актами службових розслідувань; іншими зібраними доказами.\nІснують ризики, передбачені п.п. 1, 3 ч. 1 ст. 177 КПК України, на які вказує у своєму клопотанні слідча, що полягають у необхідності запобігання спробам підозрюваного переховуватися від органів досудового розслідування та/або суду; незаконно впливати на свідків у цьому ж кримінальному провадженні.\nПри цьому, суд враховує вагомість наявних доказів про вчинення підозрюваним вказаного кримінального правопорушення, тяжкість покарання, що загрожує у разі визнання його винуватим у вчиненні кримінального правопорушення, його вік, стан здоров`я.\nСуд відхиляє доводи сторони захисту про можливість застосування більш м`якого запобіжного заходу, оскільки ч. 8\xa0ст. 176 КПК України\xa0визначено, що під час дії воєнного стану до військовослужбовців, які підозрюються або обвинувачуються у вчиненні злочинів, передбачених статтями\xa0402-405,\xa0407,\xa0408,\xa0429 Кримінального кодексу України, застосовується виключно запобіжний захід, визначений пунктом 5 частини першої цієї статті. Враховуючи те, що на даний час діє воєнний стан, до підозрюваного за\xa0ст. 408 КК України\xa0може бути застосовано лише тримання під вартою. Окрім того, суд враховує, що підозрюваний оголошувався в розшук. \nКримінальне правопорушення, яке інкриміноване ОСОБА_6 , за відомостями слідства вчинено 20.01.2023. Та обставина, що ОСОБА_6 на даний час оформив догляд за бабусею не є підставою для звільнення від кримінальної відповідальності. При цьому, як встановлено з довідок у с. Іванів зареєстровано 11 осіб, які входять до складу його сім`ї. Доказів того, що догляд за бабусею може здійснювати виключно ОСОБА_6 суду не надано.\nЗгідно з п. 4 ч. 2\xa0ст. 183 КПК України\xa0запобіжний захід у вигляді тримання під вартою не може бути застосований, окрім як, зокрема, до раніше не судимої особи, яка підозрюється або обвинувачується у вчиненні злочину, за який законом передбачено покарання у виді позбавлення волі на строк понад п`ять років.\nВраховуючи викладене та приймаючи до уваги встановлені обставини, слідчий суддя доходить висновку про наявність підстав для задоволення клопотання та обрання підозрюваному запобіжного заходу у вигляді тримання під вартою.\nПри цьому, слідчий суддя, у відповідності до абз. 8 ч. 4\xa0ст. 183 КПК України, не вважає необхідне визначати розмір застави, оскільки кримінальне провадження порушено за фактом вчинення злочину, передбаченого\xa0ст. 408 КК України.\nНа підставі вищевикладеного і керуючись ст.ст.\xa0177,\xa0178,\xa0181,\xa0183,\xa0184,\xa0193,\xa0194,\xa0395 КПК України,\n\nУХВАЛИВ:\nКлопотання слідчої СВ Хмільницького РВП ГУНП у Вінницькій області ОСОБА_7 про застосування запобіжного заходу у вигляді тримання під вартою - задовольнити.\nЗастосувати до ОСОБА_6 запобіжний захід у вигляді тримання під вартою строком 60 днів, тобто до 10:58 год 20.01.2026.\nСтрок тримання ОСОБА_6 під вартою рахувати з моменту затримання, тобто 10:58 год 22.11.2025.\nУхвала слідчого судді підлягає негайному виконанню після її проголошення.\nУхвала слідчого судді може бути оскаржена до Вінницького апеляційного суду протягом 5 днів з дня її оголошення, однак оскарження ухвали не зупиняє її виконання.\n\nСлідчий суддя\xa0\xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0\xa0 ОСОБА_8 \n\n\n\n\n\n\n\x00'

In [17]:
from uuid import uuid4

from langchain_core.documents import Document

document_1 = Document(
    page_content=rtf_texts[0],
    metadata={"source": "149/3813/25"},
    id=1,
)

document_2 = Document(
    page_content=rtf_texts[1],
    metadata={"source": "149/4141/24"},
    id=2,
)

document_3 = Document(
    page_content=rtf_texts[2],
    metadata={"source": "149/339/25"},
    id=3,
)

document_4 = Document(
    page_content=rtf_texts[3],
    metadata={"source": "149/6/25"},
    id=4,
)


documents = [
    document_1,
    document_2,
    document_3,
    document_4
]
uuids = [str(uuid4()) for _ in range(len(documents))]

vector_store.add_documents(documents=documents, ids=uuids)

['2accfa83-4e00-45cc-8e1e-a7a7daf69c21',
 '5714d8ec-5d7d-44ab-bda8-65208be4b540',
 '01f35cea-aaff-4fd5-8332-c9f9111b129c',
 '7613c3c7-96b1-48dc-9d7a-c30c2492cec6']

In [21]:
vector_store.similarity_search(
    "149/3813/25",
    k=1
)

[Document(id='7613c3c7-96b1-48dc-9d7a-c30c2492cec6', metadata={'source': '149/6/25'}, page_content='\nСправа № 149/6/25\nПровадження №2/149/219/25 \nНомер рядка звіту 40 \nУ Х В А Л А\nпро відкриття провадження у справі\n14.01.2025 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 м. Хмільник\nСуддя Хмільницького міськрайонного суду Вінницької області Олійник І. В., отримавши позовну заяву ТОВ "ФК "Кредит-Капітал" до ОСОБА_1 про стягнення заборгованості,\nВСТАНОВИВ:\nДо Хмільницького міськрайонного суду Вінницької області надійшла вказана позовна заява,, яка підсудна цьому суду, відповідає вимогам ст.ст. 175-177 ЦПК України, підстави для залишення її без руху, повернення, відмови у відкритті провадження відсутні. \nЗа змістом ст.\xa0274\xa0ЦПК України\xa0дана справа підлягає розгляду в порядку спрощеного позовного провадження.\nВиходячи з\xa0викладеного,\xa0вважаю,\xa0що у\xa0справі слід\xa0відкрити провадження\xa0 тавідповідно до ч. 5 ст. 279 ЦПК України, з власної ініціативи суду, призначити її до розгляду за правилами спрощеного позовного провадження з повідомленням (викликом) сторін.\nНа підставі наведеного, керуючись ст.ст.\xa019,\xa0175,\xa0177,\xa0187,\xa0274,\xa0277\xa0\xa0ЦПК України, суддя, \nУХВАЛИВ:\nПрийняти позовну заяву до розгляду та відкрити провадження за позовом ТОВ "ФК "Кредит-Капітал" до ОСОБА_1 про стягнення заборгованості.\nРозгляд справи здійснюватиметься за правилами спрощеного позовного провадження з повідомленням (викликом) сторін.\nПризначити судове засідання для розгляду справи по суті на\xa010:00 год 27.02.2025 в залі судових засідань Хмільницького міськрайонного суду (22000, Вінницька область, м. Хмільник, вул. Столярчука, 4).\nВизначити відповідачу п`ятнадцятиденний строк з дня вручення даної ухвали для подання відзиву на позовну заяву. У зазначений строк відповідач має право надіслати суду відзив на позовну заяву, який повинен відповідати вимогам ст. 178 ЦПК України, і всі письмові та електронні докази (які можливо доставити до суду), висновки експертів і заяви свідків, що підтверджують заперечення проти позову. Відповідно до вимог ч. 4 ст. 178 ЦПК України, одночасно з надісланням (наданням) відзиву до суду, копія відзиву та доданих до нього документів відповідач зобов`язаний надіслати\xa0 іншим учасникам справи. У разі ненадання відповідачем відзиву у встановлений судом строк без поважних причин суд вирішує справу за наявними матеріалами (ч. 8 ст. 178 ЦПК України). Відповідно до ч. 1 ст. 193 ЦПК України у строк для подання відзиву відповідач має право пред`явити зустрічний позов.\nВстановити позивачу п`ятиденний строк з дня отримання відзиву для подання відповіді на відзив, яка має відповідати вимогам ч.ч. 3-5 ст. 178 ЦПК України, копія якої одночасно з поданням до суду повинна бути надіслана іншим учасникам справи.\nВстановити відповідачу п`ятиденний строк з дня отримання відповіді на відзив для подання заперечення, яке має відповідати вимогам ч.ч. 3-5 ст. 178 ЦПК України, копія якого одночасно з поданням до суду повинна бути надіслана іншим учасникам справи.\nЗа змістом ч. 1 ст. 212 ЦПК України учасники справи мають право брати участь у судовому засіданні в режимі відеоконференції, оскільки в суді наявна відповідна технічна можливість, крім випадків, коли явка учасника справи в судове засідання визнана судом обов`язковою. \nУчасники справи можуть отримати інформацію щодо справи за веб-адресою: https://hm.vn.court.gov.ua/sud0227/. Копію ухвали, копії позовної заяви та доданих документів надіслати учасникам судового розгляду. \nУхвала\xa0оскарженню не підлягає. \n\n\xa0Суддя  \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0Ігор ОЛІЙНИК \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \n\n\x00')]

In [25]:
retriever = vector_store.as_retriever(
    search_type="mmr", search_kwargs={"k": 1, "fetch_k": 5}
)

retriever.invoke("№2/149/219/25")

[Document(id='01f35cea-aaff-4fd5-8332-c9f9111b129c', metadata={'source': '149/339/25'}, page_content='\nСправа № 149/339/25\nПровадження №3/149/286/25 \nНомер рядка звіту 208\nП О С Т А Н О В А\nІМЕНЕМ УКРАЇНИ\n\xa0 \xa0 \xa0 \xa0\n20.02.2025 року \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0м. Хмільник\nСуддя Хмільницького міськрайонного суду Вінницької області Олійник І. В., розглянувши матеріали, що надійшли від ГУ ДПС у Вінницькій області про притягнення \nОСОБА_1 , ІНФОРМАЦІЯ_1 , громадянки України, РНОКПП НОМЕР_1 , заміжньої, яка проживає за адресою: АДРЕСА_1 \nдо адміністративної відповідальності за ч. 1 ст. 163-1 КУпАП, \n\nВ С Т А Н О В И В :\n13.01.2025, під час проведення документальної позапланової виїзної перевірки податкового, валютного та іншого законодавства, контроль за дотриманням якого покладено на контролюючі органи встановлено порушення Хмільницькою міжрайонною Державною лабораторією державної служби України з питань безпечності харчових продуктів та захисту споживачів, головою комісії з реорганізації якої є ОСОБА_1 , ведення податкового обліку, а саме п. 44.1 ст. 44, п. 49.1 ст. 49, п. 184.6 ст. 184, п. 198.6 ст. 198, п. 201.11 ст. 201, пп. 266.2.1 п. 266.2, пп. 266.3.1 п. 266.3 ст. 166, пп. 266.7.5 п. 266.7, пп. 266.8.1 п. 266.8 ст. 266, п. 57.1 ст. 57, п. 287.3 ст. 287, п. 63.3 ст. 63 Податкового кодексу України внаслідок чого донараховано податок на додану вартість у сумі 2553 грн, у тому числі за травень 2024, податок на майно відмінний від земельної ділянки у загальній сумі 60484,16 грн. \nВказані дії ОСОБА_1 кваліфіковано, як адміністративне правопорушення, передбачене ч. 1 ст. 163-1 КУпАП.\nУ суді ОСОБА_1 визнала вину та підтвердила викладені у протоколі обставини.\nСуддя, заслухавши пояснення ОСОБА_1 дослідивши матеріали справи, дійшов висновку, що ОСОБА_1 своїми діями вчинила адміністративне правопорушення, передбачене ч. 1 ст. 163-1 КУпАП, що, окрім її пояснень наданих у суді, підтверджується: протоколом про адміністративне правопорушення № 28 від 13.01.2025; актом перевірки № 558/02-32-07-13/32885289 від 13.01.2025.\nПриймаючи до уваги характер вчиненого правопорушення, особу ОСОБА_1 ,\xa0яка визнала\xa0вину,\xa0раніше до\xa0адміністративної відповідальності\xa0не притягувалася,\xa0має на\xa0утриманні двох\xa0дітей,\xa0суддя дійшов\xa0висновку,\xa0що до\xa0неї належить застосувати адміністративне стягнення у виді штрафу в розмірі п`яти неоподатковуваних мінімумів доходів громадян. \nВідповідно до ст. 40-1 КУпАП, п. 5 ч. 2 ст. 4 Закону України "Про судовий збір" у разі ухвалення судом постанови про накладення адміністративного стягнення, з особи на яку накладено адміністративне стягнення, стягується судовий збір в розмірі 0,2 розміру прожиткового мінімуму для працездатних осіб.\nКеруючись ст.ст.\xa027,\xa033-35,\xa0163-1,\xa0221,\xa0280,\xa0284,\xa0294,\xa0307,\xa0308\xa0КУпАП, суддя, \n\nП О С Т А Н О В И В:\nОСОБА_1 визнати винною у вчиненні адміністративного правопорушення, передбаченого ч. 1 ст. 163-1 КУпАП та застосувати до неї адміністративне стягнення у виді штрафу в дохід держави (Отримувач коштів: ГУК у Він.обл./Хмільн.р-н/21081100, Код отримувача (ЄДРПОУ): 37979858, Банк отримувача: Казначейство України (ЕАП), Номер рахунку (IBAN): UA308999980313060106000002624, Код класифікації доходів бюджету: 21081100) у розмірі п`яти неоподатковуваних мінімумів доходів громадян, що становить 85 грн. \nСтягнути з ОСОБА_1 в дохід держави (Отримувач: ГУК у м. Києві/м.Київ/22030106, Код отримувача (ЄДРПОУ): 37993783, Банк отримувача: Казначейство України (ЕАП), Рахунок отримувача: UA908999980313111256000026001, Код класифікації доходів бюджету: 22030106) судовий збір в розмірі 605,60 грн.\nЗгідно із ч. 1 ст. 307 КУпАП, штраф має бути сплачений порушником не пізніш як через п`ятнадцять днів з дня вручення йому постанови про накладення штрафу, крім випадків, передбачених статтею 300-1 цього Кодексу, а в разі оскарження такої постанови - не пізніш як через п`ятнадцять днів з дня повідомлення про залишення скарги без задоволення. \nВідповідно до ст.\xa0308\xa0КУпАП у разі несплати правопорушником штрафу у строк, установлений частиною першою статті 307 цього Кодексу, постанова про накладення штрафу надсилається для примусового виконання до відділу державної виконавчої служби за місцем проживання порушника, роботи або за місцезнаходженням його майна в порядку, встановленому законом. У порядку примусового виконання постанови про стягнення штрафу за вчинення адміністративного правопорушення з правопорушника стягується: подвійний розмір штрафу, визначеного у відповідній статті цього\xa0Кодексу та зазначеного у постанові про стягнення штрафу; витрати на облік зазначених правопорушень. \nПостанова суду може бути оскаржена до Вінницького апеляційного суду через Хмільницький міськрайонний суд протягом десяти днів з дня її винесення.\n\n\xa0 \xa0 \xa0 \xa0Суддя \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 Ігор ОЛІЙНИК \n\n\n\n\n\n\n\x00')]

#### Neon Connect

1

,doc_id,court_code,judgment_code,justice_kind,category_code,cause_num,adjudication_date,receipt_date,judge,doc_url,status,date_publ
0,124212035,227,5.0,1.0,40356.0,149/4141/24,2025-01-02 00:00:00+02,2025-01-04 00:00:00+02,Олійник І. В.,http://od.reyestr.court.gov.ua/files/62/90134c...,1,2025-01-06 00:00:00+02
1,129579772,814,5.0,2.0,40476.0,334/6318/25,2025-08-14 00:00:00+03,2025-08-18 00:00:00+03,Турбіна Т. Ф.,http://od.reyestr.court.gov.ua/files/64/20b931...,1,2025-08-19 00:00:00+03
2,129526117,1521,5.0,1.0,40352.0,509/4270/25,2025-08-14 00:00:00+03,2025-08-14 00:00:00+03,Кириченко П. Л.,http://od.reyestr.court.gov.ua/files/64/5981b7...,1,2025-08-15 00:00:00+03
3,128243120,2029,3.0,1.0,40348.0,646/449/25,2025-06-19 00:00:00+03,2025-06-19 00:00:00+03,Черняк В. Г.,http://od.reyestr.court.gov.ua/files/64/270b13...,1,2025-06-20 00:00:00+03
4,126288303,5026,5.0,3.0,40222.0,925/1660/24,2025-04-02 00:00:00+03,2025-04-02 00:00:00+03,Гладун А. І.,http://od.reyestr.court.gov.ua/files/63/5821cb...,1,2025-04-03 00:00:00+03